### ISSUE TITLE
Unschöne Prüfung auf ersten Miniserver

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#10]
https://github.com/mschlenstedt/LoxBerry-Plugin-Weather4Lox/blob/be96834cdd5c0a91f32c80716ff4c5110f25a745/bin/datatoloxone.pl#L1690

**Comment by mschlenstedt** [comment]
Fixed with 6128371a831057a5d08daa1345f3d31af24670d3
