### ISSUE TITLE
Webseite wird nicht aktualisiert durch Abfrage des Wetter Dienst.

### ISSUE THREAD

**Issue by montecristo24de** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#100]
Hallo, 
Ich habe folgendes Problem, mein Wetter server auf dem miniserver funktioniert tadellos. Ich habe auch den Link der Webseite als Link in meiner config eingefügt. Leider werden diese Daten nicht aktualisiert. Ich meine diesen Link „ http://loxberry_IP/plugins/weather4lox/webpage.html. Erst wenn ich im Plugin manuell die Daten abrufen, werden die Daten hinter dem Link mit aktualisiert. Ich weiß in einer vorhergehenden Version war dieses anders. Ich nutze mein Loxberry mit Version :3.00.3
Mein Wetter4loxone hat die Version 4.10.0.2.

**Comment by mschlenstedt** [comment]
Auf LoxBerry 3.0.0.5 aktualisieren.
