### ISSUE TITLE
cannot save input server settings

### ISSUE THREAD

**Issue by nielsdgs** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#101]
Hi, thanks for the plugin, in vthis new version however I cannot safe the data off the server settings, get the following error. using firefox on a mac, same happens in chrome

Wide character in subroutine entry at /opt/loxberry/webfrontend/htmlauth/plugins/weather4lox/index.cgi line 1229.

**Comment by mschlenstedt** [comment]
Yes, this is because DarkSky has closed down their Service. Please change over to another weatherdata provider - I would suggest VisualCrossings.
