### ISSUE TITLE
Log "Weather4Lox DATATOLOXONE process started" is empty for regular execution

### ISSUE THREAD

**Issue by cmonty14** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#104]
Hello,
checking the logfiles I have identified that any log "Weather4Lox DATATOLOXONE process started" is empty for regular execution, means every 15min in my setup.

However, fetching weather data manually creates a logfile that includes data.

How can I fix this error?

THX
![2023-08-03_19-15](https://github.com/mschlenstedt/LoxBerry-Plugin-Weather4Lox/assets/12523591/80df1c7e-e524-4d2b-95d0-e4040a1c376b)

**Comment by mschlenstedt** [comment]
Set loglevel to debug. Your loglevel is set to error. No errors - no log entries.

**Comment by cmonty14** [comment]
Hello,
after setting log level to "debug", the log includes relevant entries.

This means, for non-regular execution the log level setting is ignored?

**Comment by mschlenstedt** [comment]
Correct. For manual executing, loglevel is always "debug", because you only need this option for trouble shooting.
