### ISSUE TITLE
Sonnenstrahlung von Wunderground wird nicht übernommen 

### ISSUE THREAD

**Issue by Ho551** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#107]
In der aktuellen Version wird der Wert der Sonnenstrahlung von Wunderground nicht in den Emulator-Datensatz geschrieben.
Als Hauptwetterservice habe ich OpenWeatherMap im Einsatz.
Der Strahlungswert bleibt bei -9999.

**Comment by mschlenstedt** [comment]
Wunderground hat nur den aktuellen Wert, also in den Emulatordaten die erste Zeile. Alle anderen bleiben auf -9999.

**Comment by mschlenstedt** [comment]
Visual Crossing hat übrigens komplette Strahlungswerte, inklusive der stundengenauen Vorhersage.

**Comment by Ho551** [comment]
Genau, mit dem Update wurde der aktuelle Wert nicht mehr übernommen. Also betrifft die erste Zeile aus den Emulatordaten.

Danke für den Hinweis mit Visual Crossing, werde ich ausprobieren.

**Comment by mschlenstedt** [comment]
Eigentlich sollte das gehen, wir haben da nichts geändert. Bitte mal Logging auf Debug stellen und hier das data2loxone Log und das Log vom WU_grabber hier anhängen. Am 17.09.2023 um 13:36 schrieb Ho551 ***@***.***>:﻿
Genau, mit dem Update wurde der aktuelle Wert nicht mehr übernommen. Also betrifft die erste Zeile aus den Emulatordaten.
Danke für den Hinweis mit Visual Crossing, werde ich ausprobieren.

**Comment by mr-manuel** [comment]
Könnte auch mit dem Post in LoxForum zusammenhängen: https://www.loxforum.com/forum/projektforen/loxberry/plugins/157182-plugin-weather4lox-ehemals-wunderground4loxone?p=403918#post403918

**Comment by mschlenstedt** [comment]
Ja, vermutlich beeinflussen sich die beiden Cronjobs gegenseitig.

**Comment by mschlenstedt** [comment]
Gefixt in neuester Version,
