### ISSUE TITLE
Wird nicht mehr unterstützt

### ISSUE THREAD

**Issue by sseidl1984** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#109]
über dns masq läuft das nicht mehr 
![Screenshot 2023-12-20 193452](https://github.com/mschlenstedt/LoxBerry-Plugin-Weather4Lox/assets/110662946/f751b2b0-1bf9-4c53-a865-35c05454e37c)

12	19:25:50.117	Zuhause		Request	dns.loxonecloud.com	/interface/api.php?a=2&ms=504FXXXXXX&h=758e1834ebf59a8ccc199ae7d5bf37b48e43ab6d	GET /interface/api.php?a=2&ms=504FXXXXXXC&h=758e1834ebf59a8ccc199ae7d5bf37b48e43ab6d HTTP/1.1\r\nHost: dns.loxonecloud.com\r\nUser-Agent: [en]\r\nKeep-Alive: 300\r\nConnection: keep-alive

11	19:24:58.002	Zuhause		Response	weather.loxone.com:6066	/forecast/?user=loxone_504XXXXXX&coord=13.0590,48.7710&asl=315&format=1&new_api=1	HTTP/1.1 200 OK\r\ncross-origin-embedder-policy: require-corp\r\ncross-origin-opener-policy: same-origin\r\ncross-origin-resource-policy: same-origin\r\nx-dns-prefetch-control: off\r\nexpect-ct: max-age=0\r\nx-frame-options: SAMEORIGIN\r\nstrict-transport-security: max-age=15552000; includeSubDomains\r\nx-download-options: noopen\r\nx-content-type-options: nosniff\r\norigin-agent-cluster: ?1\r\nx-permitted-cross-domain-policies: none\r\nreferrer-policy: no-referrer\r\nx-xss-protection: 0\r\ncontent-security-policy: default-src 'self';...

Wenn ich den link am Loxberry öffne seh ich 
![grafik](https://github.com/mschlenstedt/LoxBerry-Plugin-Weather4Lox/assets/110662946/15ef7bdf-5e32-4b86-9db7-87702a264faa)

Also daten bekomme ich 
aber der CALL über wetter.loxone.com wird nicht aufgelöst ?

**Comment by mschlenstedt** [comment]
Dein Miniserver nutzt nicht den LoxBerry als DNS Server. Hier findest Du zahlreiche Postings dazu, was Du analysieren und tun kannst: https://www.loxforum.com/forum/projektforen/loxberry/plugins/157182-plugin-weather4lox-ehemals-wunderground4loxone

**Comment by sseidl1984** [comment]
auch wenn Sie der meinung sind es leigt an dummen Usern muss ich hier wiedersprechen 
es liegt definitiv am Plugin 

![grafik](https://github.com/mschlenstedt/LoxBerry-Plugin-Weather4Lox/assets/110662946/acf09953-c545-4909-a790-0591dfcc0f7f)

da nach den Angaben des Entwickler alles korrekt eingestellt wurde 
sogar der loxberry wurde neu aufgesetzt, dennoch leider keine Wetterdaten.

Dei Fehlermeldung zeigt ja klar dass es unsichere daten sind .

4	12:55:46.091	Zuhause		Response	dns.loxonecloud.com	/interface/api.php?a=2&ms=XXXXXXX&h=758e1834ebf59a8ccc199ae7d5bf37b48e43ab6d	HTTP/1.1 200 OK\r\nContent-Length: 49\r\nContent-Security-Policy: default-src dns.loxonecloud.com *.dns.loxonecloud.com 'unsafe-inline' data:;\r\nContent-Type: text/html; charset=UTF-8\r\nDate: Mon, 01 Jan 2024 11:55:46 GMT\r\nServer: Apache/2.4.29 (Ubuntu)

Daher mal das Plugin überarbeiten

**Comment by mschlenstedt** [comment]
Meinst Du nicht, dass Deine Antwort ziemlich frech ist für ein kostenloses Plugin, was ich in meiner Freizeit entwickle? Ich muss daher hier überhaupt nichts... Wenn Dir das alles nicht passt, dann kaufe doch den kostenpflichtigen Wetterservice von Loxone. Kotzt mich an diese "Geiz ist geil" und "ich will alles umsonst" Mentalität.

Komisch ist auch, dass bei allen anderen das Plugin funktioniert, nur bei Dir nicht. Komisch auch, dass Dein Loxgauszug oben die Serversignatur "Server: Apache/2.4.29 (Ubuntu)" enthält. Der LoxBerry läuft nicht auf Ubuntu, sondern auf Debian. Nun kannst Du dreimal raten, welcher Server Dir da antwortet.

Schönen Tag noch.
