### ISSUE TITLE
Emulator

### ISSUE THREAD

**Issue by Kropiunik123** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#11]
Guten Morgen 

Ich habe den Emulator aktiviert und alle Einstellungen richtig eingestellt.
Die Wetterdaten werden aber nur 2 Tage angezeigt, danach muss ich den Miniserver neu starten.

**Comment by mschlenstedt** [comment]
Eventuell Netzwerk-Probleme? Sobald der LoxBerry für den Mniniserver nicht erreichbar ist wechselt er auf den zweiten angegebenen Nameserver in LoxoneConfig. Damit ist der Emulator quasi deaktiviert, da der Miniserver über diesen Nameserver wieder den Orignal-Loxone-Wetterserver anfragt. Bis zum nächsten Reboot.

**Comment by mschlenstedt** [comment]
Keine Antwort mehr, daher geschlossen.
