### ISSUE TITLE
Ist es möglich eine andere Wetterkarte zu brauchen?

### ISSUE THREAD

**Issue by gmkey** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#12]
Ich habe eine niederländische Übersetzung des Plugins erstellt. Ich werde dafür eine Pull-Anfrage erstellen.
 Meine Frage ist, ob es möglich ist, dass die Wetterkarten ein ortsabhängiges Auswahlmenü erstellen, das Karten von beispielsweise dem Wetter in den Niederlanden zeigt (https://www.knmi.nl/nederland-nu/weer/verwachtingen).

**Comment by mschlenstedt** [comment]
It's easy if you know a little bit HTML. The Template Files could be found here: /opt/loxberry/templates/plugins/weather4lox/themes/en

Just edit the "map"-files according your needs.

![image](https://user-images.githubusercontent.com/16830799/44312098-2fda0d80-a3f3-11e8-8307-7db3abcbfb38.png)

**Comment by mschlenstedt** [comment]
And of course we will integrate the NL maps in the dutch translation :-)

**Comment by gmkey** [comment]
great!
