### ISSUE TITLE
Fehler Plugin

### ISSUE THREAD

**Issue by glane1909** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#23]
Undefinierte Unterroutine & LoxBerry :: Web :: loglist_url wird in /opt/loxberry/webfrontend/htmlauth/plugins/weather4lox/index.cgi Zeile 378 aufgerufen.

**Comment by mschlenstedt** [comment]
Ist der LoxBerry auf dem letzten Release Stand?

**Comment by christianTF** [comment]
Geschlossen wegen Inaktivität
