### ISSUE TITLE
Speichern von Änderungen nicht möglich, wenn der API-Key geblockt ist

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#26]
Übernommen aus Wiki-Kommentar
https://www.loxwiki.eu/display/LOXBERRY/Weather4Loxone?focusedCommentId=45188961#comment-45188961

Arthur Dent sagt:
Tolles Plugin. Danke!

Mir scheint ich habe einen Bug entdeckt: Hatte des Darksky Zugang wie hier im Wiki vorgeschlagen zu Testzwecken auf minütliche Abfrage gestellt, aber dann als alles funktionierte vergessen zurückzusetzen. Fazit: nach Überschreiten der zulässigen Anzahl an Abfragen wir mein Schlüssel geblockt . Logisch. Nun will ich ein paar Tage später im Plugin die Abfragehäufigkeit ändern. Das geht aber nicht, keine Änderung wird gespeichert, weil ja die die API Probleme macht. (Fehler 403) Damit landen man in einen Deadlock, wo nur noch das Plugin deinstalliert werden kann.  .. vielleicht könnt ihr das bei Gelegenheit mal korrigieren

**Comment by mschlenstedt** [comment]
Fixed in 4.5.0
