### ISSUE TITLE
Timer beim Senden von UDP

### ISSUE THREAD

**Issue by Martin-66** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#27]
Vorausgesetzt: Mein Miniserver ist zu 92% belegt!
Wenn Weather4Loxone die current conditions, 2x daily forecasts, 24x hourly forecast und kalkulierte Werte sendet, dann empfängt (verarbeitet) der Miniserver nur mal bis etwa 12 hourly forecasts. Es ist so nicht möglich, die kalkulierten Werte zu empfangen.
Habe nach dem Senden in "datatoloxone.pl" ein "sleep(1);" reingemacht, jetzt dauert zwar die Übermittlung etwas länger, dafür bekommt (verarbeitet) mein Miniserver alle Daten - bis zu den kalkulierten.

**Comment by mschlenstedt** [comment]
Fixed in 4.5.0
