### ISSUE TITLE
Windchill in Stundenvorhersagen

### ISSUE THREAD

**Issue by Datenkrake156** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#28]

**Comment by Datenkrake156** [comment]
Hallo zusammen,
habe in der letzten Woche die ganzen UDP-Befehle für die gewünschten Werte von DarkSky in der config zusammengestoppelt. Mit der umfangreichen und detaillierten Anleitung  (vielen Dank dafür) war es eine reine Fleißarbeit. Technisch läuft es auch alles sauber. Ich habe allerdings Probleme bei der Interpretation des Windchills in den Stundenvorhersagen (hfc1, hfc3 usw.). Hier werden mir Werte von teilweise über 40♣° angezeigt. Bei den aktuellen Außentemperaturen sind solche Werte im Fieberbereich nicht glaubhaft und m.W. auch nicht von der Formel abgedeckt.

Die Werte werden aber so schon direkt von der App angeliefert, siehe Protokolldatei.
Meine Frage: tritt dieser Effekt bei Euch auch auf oder werden die Werte nur so bei mir infolge der Geoposition (Nähe Berlin) angeliefert?

Rein aufgrund der Zahlenwerte vermute ich, daß anstelle des Windchills die Windböen angezeigt werden (w_gu statt w_ch) und irgenwo auf der Verarbeitungsstrecke verdreht werden. Ehe ich bei DarkSky nachfrage, würde ich aber gerne von Euch eine Bestätigung erhalten.

Nochmals Danke für Eure kreativen Tools.

Armin 

P.S. Habe dann noch eine Frage als Anfänger, die hier eigentlich nicht hingehört:
Ich habe für die verschiedenen Abfrgen Kategorien in Loxone eingerichtet ( Wetter heute, morgen, 1h usw). Innerhalb dieser Kategorien werden die einzelnen Werte jetzt in alphabetischer Reihenfolge aufgeführt. Habt Ihr einen Trick oder einen Hinweis auf eine Anleitung, diese Reihenfolge anzupassen? Habe bei meiner (zugegebenermaßen noch nicht so intensiven) Suche noch nichts gefunden.
Nochmals Danke
Armin
['20190202_003005_073_datatoloxone.log'.txt](https://github.com/mschlenstedt/LoxBerry-Plugin-Weather4Lox/files/2825820/20190202_003005_073_datatoloxone.log.txt)

**Comment by mschlenstedt** [comment]
Fixed in 4.5.0
