### ISSUE TITLE
UDP Daten

### ISSUE THREAD

**Issue by rogersteger** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#3]
Seit kurzer Zeit werden die Daten des Wetterservices nicht mehr im MiniServer erneuert. Es scheint, dass im Plugin die Daten vorhanden sind, da die HTML Ansicht aktuell ist. Einzig der UDP Dienst an den Miniserver funktioniert nicht. Auch im Monitor sehe ich, dass keine Pakete ankommen.

Könnte es mit kürzlich veröffentlichten Sicherheitsupdates des Loxberrys zu tun haben? Ich habe den aktuellen master stand ebenfalls getestet und dort funktioniert es ebenfalls nicht. Ist dies ein generelles Problem oder scheint das nur bei mir der Fall zu sein. Gemäss LogFile sollten die Daten erfolgreich per UDP gesendet worden sein.

Ich habe natürlich alles bereits mehrmals neu gestartet, die Config neu geladen und auch die Plugins erneut installiert.

**Comment by rogersteger** [comment]
Ich kann momentan den Log Level zwar auf Debug stellen, aber es hat keinen Effekt. Egal was ich auswähle, der Level bleibt immer auf 3. Ich versuche noch ein Logfile von einer vorherigen Session zu finden. Ich sollte noch ein Logfile mit debug Level haben, wahrscheinlich aber mit der neusten Version des scripts.

**Comment by rogersteger** [comment]
[weather4lox.log](https://github.com/mschlenstedt/LoxBerry-Plugin-Weather4Lox/files/2106231/weather4lox.log)

Hier ein Auszug aus dem logfile, als das Umstellen auf Debugging noch ging.

**Comment by mschlenstedt** [comment]
Mmhh, irgendetwas ist komisch bei Dir. Scheint so, als ob Du teilweise noch auf einem alten versionsstand bist (obwohl das Logfile die richtige Version ausspuckt).

Bitte deinstalliere mal das Plugin und installiere dann den letzten Entwicklungsstand von hier (bitte nicht nur Upgrade durchführen): https://github.com/mschlenstedt/LoxBerry-Plugin-Weather4Lox/archive/master.zip

Dann bitte Loglevel nochmal auf "Debug" stellen und das Logfile hier posten. Nicht vergessen in den Einstellungen das Senden per UDP zu aktivieren :-)

**Comment by mschlenstedt** [comment]
Nein, bei Dir läuft immer noch die alte Skript-Version. Entweder hast Du das falsche Pluginarchiv installiert oder er schafft es nicht mehr, die Datei bei der Deinstallation zu löschen. Es muss datatoloxone.pl Version 4.3.3 sein, bei Dir ist es laut Logfile noch 4.3.2.

[code]
<INFO>Weather 4 Loxone Version 4.3.2
<INFO>Loglevel: 7
This is ./datatoloxone.pl Version 4.3.3
[/code]

Deinstalliere bitte mal das Plugin nochmal. Dann mit dem Filemanager-Widget mal in das Verzeichnis /bin/plugins wechseln und schauen, ob dort nach der Deinstallation das Verzeichnis weather4lox noch exisitert. Wenn ja bitte schauen wem das Verzeichnis gehört. Es muss loxberry:loxberry sein (siehe Screenshot). Dann das Verzeichnis löschen.

![image](https://user-images.githubusercontent.com/16830799/41496099-66b03864-7137-11e8-9af6-d2de4c5f87c8.png)

Dann nochmal das Master-Archiv herunterladen (Link siehe oben) - vielleicht mal mit einem anderen Browser, um irgendwelche Cache-Effekte auszuschließen. Dann nochmal installieren.

**Comment by rogersteger** [comment]
Vielen Dank für die Infos. Ich werde es ausprobieren, bin aber momentan unterwegs. Ich melde mich sobald ich es testen konnte.

**Comment by rogersteger** [comment]
Nach dem löschen des scripts war das directory im Filemanager weg. Der Owner vorwer war korrekt (loxberry:loxberry). Siehe Screenshot:
![cap_delete](https://user-images.githubusercontent.com/23507846/41853837-0b3b6e9a-788f-11e8-9e1c-00d90634c0d9.jpg)

Nach der erneuten Installation sieht der log soweit ich sehe korrekt aus:
_This is /opt/loxberry/bin/plugins/weather4lox/datatoloxone.pl Version 4.3.3_

Das logfile dazu:
[weather4lox.log](https://github.com/mschlenstedt/LoxBerry-Plugin-Weather4Lox/files/2133358/weather4lox.log)

Die Daten werden gemäss logfile und Html Ansicht erneuert, per UDP werden sie allerdings nicht verschickt oder kommen nicht an. Die Daten werden in Loxone nicht angezeigt, auch nicht im UDP Monitor.

**Comment by mschlenstedt** [comment]
Ja, das passt jetzt. Und im Log sieht auch alles gut aus. Hast du denn im Miniserver einen virtuellen UDP Eingang angelegt, der auf Port 7000 lauscht? Die IP des Miniservers ist auch korrekt?

IP:192.168.0.120 Port:7000

**Comment by rogersteger** [comment]
Ja klar habe ich virtuelle Eingänge gemacht. Es hat auch seit längerem funktioniert. Erst Mitte Juni wurden die Daten nicht mehr aktualisiert. Mit dem Wireshark sieht man, dass keine UDP Pakete versendet werden. Ich frage mich ob es mit den Sicherheitsupdates des Loxberrys zu tun hat. Ansonsten habe ich nichts geändert.
Aber eigene scripts auf dem Loxberry senden Daten per UDP, auch andere Loxberry plugins senden Daten.

**Comment by mschlenstedt** [comment]
Mmmhh, ich kann das aktuell nicht nachvollziehen. An den Sicherheitsupdates kann es nicht liegen. 

Ich mache heute Abend mal eine frische LB Installation und teste das dann nochmal durch.

**Comment by mschlenstedt** [comment]
Thanks. Pull Request merged (and I also redited datatoloxone.pl to handle -9999 also).
