### ISSUE TITLE
Bewölkung am nächsten Tag

### ISSUE THREAD

**Issue by blappm** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#30]
Hallo,

Ich fände sowas ganz nett (vorausgesetzt man hat Bewölkungsdaten für den nächsten Tag).

Ich habs bei mir mal reingehackt, und es funktioniert ganz gut. Ich brauche genau diesen
Wert im Frühling und Herbst um je nach dem die Heizung anzuwerfen oder auch nicht,
wenn es am nächsten Tag schön ist, und die Sonne mein Haus gratis aufheizt. Die bestehenden Texte zur Bewölkung sind leider zum Berechnen unbrauchbar.

# Print average sky the next day
my $solhours = 0;
my $cloudpercentage = 0;
for ( my $i = 0; $i < $hourarray[-1]; $i++ ) {
        if ((int($hourarray[$i]) > (int($cur_sun_r_hour) + 1)) && (int($hourarray[$i]) < (int($cur_sun_s_hour) - 1))) {
                $solhours++;
                $cloudpercentage += $skyarray[$i];
        }
}
$cloudpercentage = int($cloudpercentage / $solhours);

$name = "dfc1\_sky";
$value = $cloudpercentage;
&send;

**Comment by mschlenstedt** [comment]
Kannst Du mal das ganze Skript bitt ehier anhängen? Was sagt der Wert aus? Durchschnittliche Bewölkung an dem Tag zwischen Sonnenauf- und Untergang?

**Comment by mschlenstedt** [comment]
Leider keine Rückmeldung -> Close.
