### ISSUE TITLE
Prüfung auf ungültige Werte bei Loxgrabber 

### ISSUE THREAD

**Issue by jo-21** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#31]
In Loxgrabber.pl sollte auf klar ungültige Werte geprüft werden. 
Das würde es ermöglichen, in Loxone Ersatzwerte zu definieren, die dann von Loxgrabber zuverlässig als ungültig erkannt werden und dann nicht zum setzen des Wertes führen.

Beispiel: Grabbing von Weatherunderground mit maxage. Fällt die Wetteranlage aus, gibt es keine Ergebnisse, Loxone schickt ungültige Ersatzwerte, Loxgrabber erkennt das und Darksky-Werte werden nicht überschrieben.

**Comment by mschlenstedt** [comment]
Fiexed
