### ISSUE TITLE
Weather4Lox

### ISSUE THREAD

**Issue by JoKdD** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#32]
Hallo, 

habe gerade das Plugin eingerichtet und es funktioniert bestens - danke für die Entwicklung, ich hatte früher bereits Wunderground genutzt und der Umstieg war dadurch sehr leicht.
Mir sind drei Dinge aufgefallen, die nicht funktionieren:
- In dem Emulator in Loxone wird die Wettervorhersage für übermorgen auch als "Heute" angezeigt.
- im Emulator wird bei aktueller Uhrzeit 16:30 Uhr als nächste Voraussage erst 23 Uhr angezeigt, obwohl die Stundenvorhersage entsprechend ausgewählt ist. Die Zeit vom Miniserver und Loxberry sind korrekt eingestellt. Jetzt um 17:06 wird die aktuelle Zeit im Emulator mit 01:00 Uhr angezeigt.
- 22 | cur_sr | Solar Radiation | W/m² wird nicht angezeigt, bei Wunderground ging es. Liefert Darksky diese Werte nicht mit?

Gruß
![Weather](https://user-images.githubusercontent.com/49368762/55685338-33f07680-5955-11e9-935e-86d9c9bd5de6.jpg)

**Comment by mschlenstedt** [comment]
Das liegt daran, das snicht genug Vorhersagedaten vorhanden sind. Dann kommt die Anzeige in der App durcheinander. Irgendetwas passt da bei Dir noch nicht. Zeitzone auf dem Loxberry gleich der des Miniservers? Alles mal neu gestartet? Letzte Version vom LoxBerry und Plugin benutzt Du?

Solar Radioation bietet DarkSky nicht.

**Comment by mschlenstedt** [comment]
Keine Antowrt -> Close.

**Comment by JoKdD** [comment]
Hallo mschlenstedt, sorry war die letzten Tage nicht greifbar.
Die Zeiten im Loxberry und Loxone / tatsächliche Uhrzeiten stimmen überein und ich habe überall die aktuellste Version drauf. Neu gestartet habe ich beides auch mal jedoch ohne Erfolg.
Klappt es sonst bei allen Usern?!

**Comment by JoKdD** [comment]
Hallo mschlenstedt, sorry war die letzten Tage nicht greifbar und du hast den Thread ja geschlossen.
Die Zeiten im Loxberry und Loxone / tatsächliche Uhrzeiten stimmen überein und ich habe überall die aktuellste Version drauf. Neu gestartet habe ich beides auch mal jedoch ohne Erfolg.
Klappt es sonst bei allen Usern und hast du noch eine Idee warum die Zeit so abweicht?! 
Danke
Gruß JoKD (Jochen)
