### ISSUE TITLE
Weatherbit keine Daten

### ISSUE THREAD

**Issue by montecristo24de** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#36]

**Comment by montecristo24de** [comment]
Harald Hahn sagt:
Hallo Zusammen.
Jetzt muss ich hier mal um Hilfe bitten. Auf Github komm ich wegen mangelnder Englisch-Kenntnisse nicht weiter.. SRY
Das Problem:
Am 23.4. schien die Weatherbit-Seite abgestürzt. Die Internet-Seite war nicht erreichbar und somit auch keine Wetterdaten. - Die Seite ist mittlerweile wieder online, aber die Einbindung in Loxone klappt nicht. Hab sogar ne 2. Registrierung mit anderer API getestet, aber immer wird im LOG-File der Fehler 403. Und freie Abfragen sind noch zu genüge da..... Jemand eine Idee?
Bis zum Absturz der Internetseite funktionierte alles wie gewünscht...
Hab bis auf weiteres erstmal auf Dark-Sky gewechselt....  

Dieses Problem habe ich auch. Gruß Thomas

**Comment by mschlenstedt** [comment]
Was soll ich denn jetzt hier machen?! WeatherBit hat Euch blockert. Warum? Keine Ahnung. Aber wie soll das denn das Plugin nun lösen?

**Comment by montecristo24de** [comment]
Hallo,
Okay, Ich glaube wir reden aneinander vorbei, 
Ich habe gestern um sicher zu gehen, einen neuen Account bei weatherbit aktiviert (seperate E-mail).

Im Plugin neuen Key eingegeben 
Wetterdaten überprüfen:  auf 60 min gestellt /raspberry und Miniserver neu gestartet

LOG Level auf debug gestellt. 

Es kommen Daten an! auf der LOG Seite des Plugins  unter Gruppe ‚Grabber_weatherbit‘ wird jedes mal critical Fehler ausgegeben.

ankommen tun folgende Daten
-current
-forcast/daily
-forcast/hourly
-forcast/3hourly —> Fehler Failed to fetch data for lat=53.6658708&lon=10.4682365. Status Code: 403

http://api.weatherbit.io/v2.0/forecast/3hourly?key=7a5a75fe5e304c9c80dac13dc189bdda&lat=53.6658708&lon=10.4682365&lang=de&units=M&marine=f
 
wenn ich den Link im Browser offne kommt als antwort :
{"error":"Your API key does not allow access to this endpoint.“}
Seit dem 23.04.2019 bekomme ich keine Daten mehr für Sonnenschein, und Abs.Strahlung.
http://Loxberry-IP/plugins/weather4lox/webpage.html —> Die Seite wird nicht mehr vom Plugin Aktuallisiert. Das Datum alles bleibt alt.
Die Wetterdaten in der Loxone App Oben linke Ecke  sind aber aktuell. 

Anbei dass Log. 

Bitte mach es so, dass ich Sonnenschein und Abs.Strahlung wieder empfange.

**Comment by mschlenstedt** [comment]
Ja, Weatherbit an den Zugriff auf den hourly Forecast blockiert. Du bekommst den nicht mehr mit der freien API. In der nächsten Version wird der Grabber trotzdem weitermachen (ist schon implementiert). Aber Du bekommst die Daten trotzdem nicht mehr, weil Weatherbit das blockiert. Da kann ich nichts machen.

Stelle auf DarkSky um.
