### ISSUE TITLE
Moon Illumination "cur_moon_p"

### ISSUE THREAD

**Issue by bobbythemoh** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#37]
Hallo,

Ich habe vor einiger Zeit auf Dark Syk umgestellt, dabei ist mir aufgefallen, dass die der Parameter "Moon Illumination (cur_moon_p)" meiner Meinung nach nicht Richtig ist.

Was auffällt:
05.05.2019 war Neumond
18.05.2019 ist Vollmond
Das Plugin zeigt jetzt 2% an, wobei wenn man es rechnet hat man 4% bzw. immer nur die Hälfte.
So wie ich den Parameter verstehe entsprechen 0% Neumond und 100% Vollmond. In der DarkSky Doku findet man jedoch:

[DarkSky](https://darksky.net/dev/docs)

moonPhase optional, only on daily
The fractional part of the lunation number during the given day: a value of 0 corresponds to a new moon, 0.25 to a first quarter moon, 0.5 to a full moon, and 0.75 to a last quarter moon. (The ranges in between these represent waxing crescent, waxing gibbous, waning gibbous, and waning crescent moons, respectively.)

MFG

**Comment by mschlenstedt** [comment]
Wie müsste man denn Deiner Meinung nach den Wert umrechnen, damit es wieder zu 0-100% passt? einfach x2?

**Comment by bobbythemoh** [comment]
Hallo, nein ganz so einfach ist es nicht mmN.

0 -->0%
0,1 --> 20%
0,2  -->40%
0,3  --> 60%
0,4 --> 80%
0,5 -->100%
0,6  --> 80%
0,7 --> 60%
0,8  -->40%
0,9  -->20%
0,9999  -->0%

**Comment by bobbythemoh** [comment]
Wenn "Value" <=0,5 -->Value *2
Sonst (1-Value)*2

**Comment by mschlenstedt** [comment]
Ok, installiere mal bitte den aktuellen master: https://github.com/mschlenstedt/LoxBerry-Plugin-Weather4Lox/archive/master.zip

Da wird es jetzt so berechnet. Müssten wir nur mal schauen, ob es jetzt bis zum Vollmond und bei abnehmendem Mond alles passt.

**Comment by bobbythemoh** [comment]
Hallo,
Bisher hatte ich einen Wert von 2% für das heutige Datum (cur_moon_p@2)
Hab es installiert. Nach dem Update Zyklus der Wetterdaten (3 Min bei mir) habe ich 4% (cur_moon_p@4). Sieht gut aus soweit. Danke für das schnelle Ändern, werde es beobachten.

**Comment by bobbythemoh** [comment]
Hallo, am 18.05. war Vollmond, da hatten wir 100%, jetzt ist abnehmend und es wurden gestern 94 un heute 82% angezeigt. Sieht gut aus. Danke für das Einarbeiten!

**Comment by mschlenstedt** [comment]
Formatierung im Webpage-Baustein haut noch nicht hin:

![image](https://user-images.githubusercontent.com/16830799/58765632-51b51300-8575-11e9-8000-f46914d6d630.png)

**Comment by mschlenstedt** [comment]
Fixed some time ago - did not remember exactly ;-)
