### ISSUE TITLE
Installation auf LB0.2.3 erfolgreich, aber kein Plugin aufrufbar

### ISSUE THREAD

**Issue by derhoeppi** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#39]
Ich möchte / muss das Plugin Wunderground4Loxone ablösen und wollte nun dieses hier nutzen. Bevor ich das alte deinstalliere, möchte ich dieses zum Laufen bekommen. Laut Loxwiki ist dieses Plugin kompatible zu Version 0.2.3 des LB. Die Installation des Plugins läuft durch. Der LB hat die aktuellen OS Updates. Beim Aufruf des Plugins erhalte ich nur ein "Error loading Page" bzw. einen HTTP Code 404 mit dem Hinweis "Die Adresse /admin/plugins/weather4lox/index.cgi gibt es hier leider nicht. ". Die Datei konnte ich im Verzeichnis "/opt/loxberry/webfrontend/html/plugins/weather4lox/" nicht finden. Auch das Verzeichnis "/opt/loxberry/webfrontend/cgi/plugins/weather4lox" ist leer.

**Comment by derhoeppi** [comment]
[Weather4Lox_4.5.0.Log](https://github.com/mschlenstedt/LoxBerry-Plugin-Weather4Lox/files/3178984/Weather4Lox_4.5.0.Log)
Hier noch das Install-Log.

**Comment by christianTF** [comment]
![642E9BDB-B5E5-4972-BB1F-3F1D7D6AB8B9](https://user-images.githubusercontent.com/14220265/57719907-fc29cc80-7680-11e9-81a2-144dd558b7aa.png)

LoxBerry 0.2.3 ist sowas von ROT!
Wo hast du das mit der Kompatibilität gelesen?

Erforderlich lt. Wiki: LB1.2.5+

**Comment by christianTF** [comment]
BTW Deswegen gibt es das LoxBerry 0.2.4 Upgrade - das verhindert die LB1.x-Plugin-Installation.

**Comment by derhoeppi** [comment]
Egal ob rot oder nicht - warum wird die nicht unterstütze Version gelistet? Das stiftet nur Verwirrung, den erwähnt wird die aktuelle Version <1. Eine solche Kompatibilitätsmatrix ist mir von anderen Softwareanbietern nicht geläufig.
Upgrade auf LB >1 geht derzeit nicht, weil noch andere Dinge darauf laufen, die ich verlieren würde. Da passt mir das Konzept für das individuelle Anpassen des LB nicht.

**Comment by mschlenstedt** [comment]
Du bist der Erste, der das mit der roten Versionsnummer nicht kapiert hat. 

Ist Dir sicherlich von anderen Softwareanbietern nicht bekannt, aber wir haben eben noch lange die alte LB Version unterstützt und da war das halt grün.

**Comment by derhoeppi** [comment]
Das kapieren ist eine Sache. Eine Legende zur farblichen Markierung gibt es nicht, so dass ich davon ausgehe, dass alle gelisteten Versionen unter dem Punkt Kompatibilität funktionieren. Das soll dann hiermit auch nur ein Hinweis sein.
Als Systemadministrator bin ich froh solche Softwarekompatibilitätsmatrixen im professionellen Umfeld nicht vorzufinden. Wenn die LB Version nicht kompatibel ist, sollte sie dort nicht stehen oder aber ein Hinweis „Kompatibel ab Version 1“. Das wäre eindeutig und führt nicht zu Verwirrungen.

**Comment by mschlenstedt** [comment]
Na, da bin ich ja froh, dass du dich sonst nur im
professionellen Umfeld bewegst.  Da ist es ja ein Leichtes für dich, Dir das Plugin selbst auf deinen 0.2.3 zu portieren. Viel Erfolg!

**Comment by christianTF** [comment]
Schlauberger 🤔
https://www.loxwiki.eu/display/LOXBERRY/Plugins

**Comment by derhoeppi** [comment]
Schade das ich jetzt eine unterschwellige Arroganz vernehmen muss. Ich bin froh das es Leute mit ausreichend Freizeit gibt, die den LB und die Plugins entwickeln und pflegen. Dafür habt ihr meine Anerkennung und auch den Respekt für die Zeit die ihr hier und im Forum investiert. 
Der Ton der jetzt hier aber auch teilweise im Forum aufkommt, ist alles andere als sachlich und konstruktiv. Für mich war die Angabe zur Kompatibilität nicht eindeutig und darauf habt ihr mich hier hingewiesen. Dazu habe ich nur den Kommentar gegeben, dass ich diese Angabe, wie ihr sie macht von keinem anderen professionellen / kommerziellen Softwaranbieter gewohnt bin, weshalb ich ja eben dieses Issue geöffnet habe.

**Comment by christianTF** [comment]
![5957AA70-D40F-4EBD-8275-119B1DB0109F](https://user-images.githubusercontent.com/14220265/57727781-a3fbc600-7692-11e9-88fc-477570fd3827.png)

Solche Matrixen sind ganz normal! Deswegen disqualifiziert dich deine „ist nicht professionell“ Aussage, was soll man da denn sagen, außer dich darauf aufmerksam machen...?

**Comment by svethi** [comment]
Es ist und bleibt kostenlose Open-Source Software. Ob man da Professionalität erwarten kann/muss/sollte, muss jeder für sich entscheiden. Als professioneller Systemadministrator, der Du ja sein willst, ist ein Loxberry 0.2.3 ein absolutes No-Go. Aus Deinem professionellen Umfeld solltest Du es ja gewohnt sein, dass es absolut notwendig ist, seine Systeme aktuell zu haben.
Im Übrigen wärest Du dann über derartige Probleme gar nicht erst gestolpert.

**Comment by derhoeppi** [comment]
Hallo Leute,
Christian sein letzter Kommentar mit dem Auszug aus einer anderen Matrix verdeutlicht es meiner Meinung nach sehr gut. Dort wird die Kompatibilität mit einem Ja oder Nein angegeben. Die farbliche Hinterlegung soll es nur noch einmal optisch verdeutlichen, die eigentliche Aussage wird jedoch mit Ja / Nein getroffen. Genau mit diesen Arten von Matrixen bin ich vertraut und finde sie auf einen Blick verständlich. Bitte nicht falsch verstehen. Ich habe gedacht ein Installationsproblem zu haben, bei dem ihr mich darauf hingewiesen habt, dass meine LB Version nicht unterstützt wird. Für mich war und ist die Kennzeichnung, wenn man sich nur das Plugin ansieht nicht eindeutig, weshalb ich es Euch mitgeteilt habe (davon lebt ja eine Community). Was ihr daraus macht ist selbstverständlich eure Sache. Aus meiner Sicht war das sachliche Kritik nur eben mit der Wertung das ich die Darstellung aus dem Loxwiki zur Kompatibilität nicht gewohnt bin. 
 
Mein LB 0.2.3 wird mit Jessie im Unterbau betrieben und dafür gibt es noch bis 2020 Kernelupdates, so dass dieses Version noch aktuell und sicher betrieben wird. Ich mache mir dahingehend keine Gedanken zumal der Raspi nur über einen Proxy auf bestimmte URL's zugreifen kann. Die Gefahr eines angreifbaren oder kompromittierbaren Systems ist bereits durch andere Maßnahmen deutlich reduziert worden.
Prinzipiell habt ihr sicherlich Recht mit dem Update auf eine aktuelle LB Version (um alle Funktionen zu nutzen), aber wie ich in einem anderen Kommentar geschrieben habe, laufen noch andere Dinge neben den Plugins auf dem Raspi, wofür es keine Plugins gibt und die Erstellung eines Plugins für diese Dinge nicht lohnt. Somit ist der LB in der aktuellen Version für einen normalen Loxone Nutzer, der ein paar Funktionen über die Plugins erweitern möchte eine feine Sache, wenn aber abseits davon Erweiterungen oder Anpassungen mit auf dem LB laufen sollen (so mein Kenntnisstand nach dem Release von Version 1.0) sind diese bei jedem Update verschwunden. Wenn ihr das jetzt verneint, würde ich mir mal die Arbeit machen und meine LB Installation zu portieren.

**Comment by christianTF** [comment]
Wir überarbeiten die Plugin-Ansicht und werden nur noch die LoxBerry-Mindestversion aufführen. Eine getrennte Anzeige für LoxBerry 0.2.x und LoxBerry 1.x (die wir eben für den Fall, dass jemand seinen alten LB weiter betreiben möchte) wird es nicht mehr geben.

Wir werden aus dem Wiki (abgesehen von den Plugin-Seiten) alle Verweise und Seiten zu LoxBerry 0.2.3 entfernen.

Bezüglich eigene Scripte und Webseiten haben wir einen eigenen Ordner am LB: https://www.loxwiki.eu/display/LOXBERRY/Eigene+Webseiten+und+Scripte+am+LoxBerry+betreiben

Für Dateien, die in /opt/loxberry/system gelinkt sind, besteht ein gewisses Restrisiko, dass wir diese mal bei einem Update patchen müssen. Wir achten weitestgehend darauf, dass es sich wirklich um Patchen und nicht um Ersetzen handelt.

lg, Christian
