### ISSUE TITLE
x86: Weather Emulator funktioniert nicht OOTB

### ISSUE THREAD

**Issue by gahujipo** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#41]
Habe weather4loxone vor ein paar Tagen installiert und nun auf in folgendem Image zum Laufen gebracht: https://www.loxwiki.eu/display/LOXBERRY/Hyper-V

Das, was nach der Installation noch manuell zu erledigen war:  

1. dnsmaq.conf Eintrag fehlte: 
```
address=/weather.loxone.com/<IPAddress>
```

2. Die weather4loxone Webseite war nicht im Apache aktiviert.
```bash
a2ensite 001-weather4lox
systemctl reload apache2
```

**Comment by mschlenstedt** [comment]
Wenn du den Emulator in der Plugin Config aktivierst und speicherst, wird die Konfiguration automatisch durchgeführt.  Reboot ist notwendig. 

Zumindest auf dem offiziell unterstützten Raspberry Image.

**Comment by gahujipo** [comment]
Leider ist das hier eben nicht der Fall. Reboot und Speichern habe ich mehrfach in verschiedenen Kombinationen versucht. Würde das Plugin eben gerne versuchen x86-kompatibel zu machen, damit es out of the box funktioniert.

**Comment by mschlenstedt** [comment]
Ok, dann muss es am Image liegen. Ich kann aus Zeitgründen die ganzen anderen Images nicht unterstützen. Das muss sich der Imagebauer anschauen, was er da gemacht hat.

**Comment by gahujipo** [comment]
Genau. Schicke in Kürze eine PR. Muss den Code vorher nur noch auf einem Raspberry testen.

**Comment by gahujipo** [comment]
Du hast vermutlich Recht, dass es am Image liegt. Das Problem tritt auf, bei der Ausführung von  
https://github.com/mschlenstedt/LoxBerry-Plugin-Weather4Lox/blob/bef6aad48800261e3a9fa87082e50481e6e10097/webfrontend/htmlauth/index.cgi#L322

Wenn dieser Befehl als User loxberry ausgeführt wird, kommt die Passwortabfrage von sudo. Das muss ich noch etwas genauer untersuchen. 

Nichts desto trotz scheint aber das Script für den Fall, dass der Cloudemu wieder deaktiviert werden soll, ohnehin gar nicht funktioniert zu haben. Details dazu und der fix in PR #42

**Comment by gahujipo** [comment]
Das Hyper-V Image wurde auf die neueste Version von Loxberry gebracht, die Änderung für [Punkt 5.2](https://www.loxwiki.eu/pages/viewpage.action?pageId=20874582#EigenesImageerstellen(LoxBerryV1.x)-5.2Berechtigungensetzen) angewandt und auf dem [FTP](https://download.loxberry.de/stable/images/hyper-v/) veröffentlicht. 
[Forumsbeitrag](https://www.loxforum.com/forum/projektforen/loxberry/allgemeines-aa/111581-hyper-v-image-für-windows?p=205551#post205551)
