### ISSUE TITLE
Openweathermap integrieren

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#45]
https://openweathermap.org/darksky-openweather

**Comment by 4paulpak** [comment]
Hi Michael, I have been working in parallel on OpenWeatherMap Integration the last days and just saw that you did it as well. Anything I can support you with?

**Comment by mschlenstedt** [comment]
@4paulpak  Thanks - I had already finished the grabber :-)

**Comment by mschlenstedt** [comment]
Added with 3005c735bda9a9af32a7e2d7486785b5aa6be80f
