### ISSUE TITLE
Wrong data mapping for solar radiation with weatherbit

### ISSUE THREAD

**Issue by ichderalex** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#48]
I´m using Weather4Lox in version 4.7.0.3 and loxberry with version 2.0.1.3.
As primary weather service, I´m using Weatherbit.

The mapping of solar radiation is wrong. I think it´s mapped to "ghi" and not to "solar_rad". Because of this, solar radiation is way too high in Loxone.

**Comment by mschlenstedt** [comment]
Weatherbit.io offers several values for solar radiation:

![image](https://user-images.githubusercontent.com/16830799/80669075-ce14e680-8aa3-11ea-8d32-68962f8a9bd7.png)

I currently use GHI, but while reading the description above, this seems to be wrong. Maybe solar_rad is the better options. All others seems to be (calculated?) values at clear sky.

Can you give me your coordinates please for comparison?

**Comment by ichderalex** [comment]
Sure, my coordiantes are:
49.52, 8.75

GHI was yesterday over 800 and there was no sun. solar_rad was at 300.
Today, GHI is at 420 and it´s raining and cloudy. Solar rad is at 42.
