### ISSUE TITLE
race-condition bei der Abfrage verschiedener Quellen

### ISSUE THREAD

**Issue by 65bitchris** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#52]
ich frage Wetterdaten über die OpenWeatherMap ab und ergänze diese mit einer Wunderground Station in meiner Umgebung.
VonWunderground interessiert mich hauptsächlich der Strahlungswert.
Leider bekomme ich immer wieder sporadisch die Werte -9999 angezeigt 
siehe screenshot.
![Strahlung](https://user-images.githubusercontent.com/68001322/86894060-ceb0a580-c102-11ea-89f7-19d644da876a.png)

Polling alle 5 minuten. 
Übergabe der Daten an Loxone per Emulation

ich habe bereits analysiert, dass das File:
/opt/loxberry/log/plugins/weather4lox/current.dat immer wieder kurzfristig (1-2 Sekunden) den Wert -9999 beinhaltet, bevor er wieder auf den Wert der Wunderground-Station springt.

Meine Vermutung, die Werte werden von den möglichen Quellen gepolled, und immer direkt in das File geschrieben.
Wenn nun von Openweather keine Daten (-9999) kommen, werden die in das File geschrieben - kurz darauf wird die Wunderground-Station gepolled und überschreibt -9999 mit dem aktuellen Wert.
 
Die Loxone polled dann sporadisch die -9999 und arbeitet mit falschen Werten.

**Comment by 65bitchris** [comment]
Es handelt sich natürlich um Strahlung absolut !

**Comment by mschlenstedt** [comment]
Die Werte werden erst aktiviert und an Loxone gesendet, wenn alle Grabber nacheinander durchgelaufen sind. Somit "sieht" Loxone nur die ersetzten Werte.

Ich habe aber das gleiche Problem mit meiner Wetterstation bei Wunderground. "Ab und zu" sendet sie anscheinend einen Strahlungswert von "0" (z. B. permanent nachts). Das scheint Wunderground manchmal so zu interpretieren, dass der Strahlungswert nicht vorhanden ist und stellt ihn nicht auf der Webseite dar. Der Grabber findet den Wert dann niht und setzt ihn auf -9999. 

Du kannst mal versuchen das Logging auf "Debug" zu stellen. Dann siehst Du auch, wenn der Grabber einen der Werte nicht findet und ihn durch -9999 ersetzt.

Ich filtere ungültige Werte <0 mit einem Statusbaustein heraus.

![image](https://user-images.githubusercontent.com/16830799/87113071-b8732880-c26d-11ea-99b4-9cba94657945.png)

![image](https://user-images.githubusercontent.com/16830799/87113031-a72a1c00-c26d-11ea-81af-ec747695bff2.png)

**Comment by 65bitchris** [comment]
ich sende nun die Werte per UDP an den Miniserver, filtere alles kleiner -1 raus (somit erkenne ich immer noch, ob ich Werte habe,  bekomme aber nicht -9999 in die Statistik), dann noch einen gleitenden Mittelwert über 1h (60/60) drüber und dann auf den Merker w4l_cur_sr. dazu habe ich den Loxone_grabber aktiviert, da ich nun diesen berenigten Wert über die Emulation wieder zurück in die Loxone geben möchte.
Leider habe ich immer noch jede volle Stunde für 10 minuten einen Wert von -9999 in der Loxone.
Alle aufbereiteten Werte habe ich mir zum debuggen angschaut - die sind sauber.
Ich komme immer noch zu dem Schluss, dass das Plugin hier nicht wie erwartet funktioniert.
Update-interval im W4L steht bei mir auf 5 Minuten.

Nach meinem Verständnis muss der Wert, der vom Loxone-Grabber kommt auf jeden Fall prio haben und alle anderen Werte aus anderen Quellen im w4l überschreiben. 
ein -9999 dürfte somit gar nicht mehr auftauchen - was wieder darauf hindeutet, dass für kurze Zeit ein nicht valider Wert von der Emulation bereitgestellt wird.

**Comment by mschlenstedt** [comment]
So ist es auch. Hier findest Du den Code, der ausgeführt wird: https://github.com/mschlenstedt/LoxBerry-Plugin-Weather4Lox/blob/master/bin/fetch.pl

Zeile 86: Daten werden vom Wetterservice geholt
Zeile 96: Forecast-Daten werden von anderen Wetterservices geholt (falls konfiguriert)
Zeile 130: Daten werden von Wunderground geholt, falls aktiviert
Zeile 138: Daten werden vom FOSHK-Plugin geholt, falls aktiviert
Zeile 146: Daten werden vom Miniserver geholt, falls aktiviert
Zeile 154: Daten werden an den Miniserver per UDP gesendet

Das alles geschiet in der angegebenen Reihenfolge. Somit überschreibt der LoxoneGrabber immer alle anderen Daten. Und erst DANN werden die Daten an den Miniserver gesendet.

Keine Ahnung wo die -9999 herkommen, aber ich kann da keinen Fehler finden.

**Comment by christianTF** [comment]
Ich hab auch mal rein geschaut, ich sehe nichts, was den Loxone Grabber veranlassen würde, deinen Datensatz NICHT zu übernehmen.

> Ich komme immer noch zu dem Schluss, dass das Plugin hier nicht wie erwartet funktioniert.

Wenn das eh jede Stunde für 10 Minuten auftritt, dann solltest du einfach mal DEBUG aktivieren (wie Michael eh schon geschrieben hat) und das Log übermitteln.

Ich schätze aber, nachdem nun 2 Monate vergangen sind, dass das Problem nicht mehr vorhanden ist.
