### ISSUE TITLE
Feature Request - average Values für schnell schwankende Messwerte

### ISSUE THREAD

**Issue by 65bitchris** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#53]
die Strahlungswerte schwanken bei leicht wolkigem Himmel teilweise stark. Da die Loxone nur alle 1h die Werte vom Wetterserver holt (in dem Fall von einer Wunderground Station über Emulation) bekommt man hier immer nur einen Momentwert, der ggf. nicht die derzeitige, durchschnittliche Strahlung widerspiegelt.
Als Idee, das Plugin könnte aus den Werten der letzen 1 oder 1,5h (einstellbare Parameter) einen Durchschnittswert (plus oder auswählbar ggf. min/max) zur Verfügung stellen. 
Somit hätte man einen "vernünftigeren" Strahlungswert.

Denkbar wäre dieses Verfahren auch für andere Messwerte.

**Comment by mschlenstedt** [comment]
Für die Weiterverarbeitung der Werte empfehle ich Dir nicht die von Loxone vorbereiteten Variablen zu verwenden. Denn wie Du richtig schreibst, werden diese viel zu selten aktualisiert. 

Aktiviere die Übertragung per UDP. Da bekommst Du aktuelle Werte jedes Mal, wenn das Plugin vom Service die Daten abholt. Schwankende Werte egalisierst Du mit einem gleitenden Mittelwert.

Ich möchte im Plugin die Werte möglichst nicht verfälschen. Der nächste möchte vielleicht die ganzen Schwankungen sehen, die Dich stören.
