### ISSUE TITLE
w4l_cur_sr not grabbed by Loxone Grabber

### ISSUE THREAD

**Issue by ChutneyMary** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#54]
Running Loxberry v2.0.1.3 and Weather4Loxone v4.8.0.1. 

I have a Virtual HTTP input labelled w4l_cur_sr. It successfully pulls data and displays a value. eg. 550 W/m².

'Test Emulator' always shows -9999. Solar Radiation in Loxone Weather page always shows 0 - 20%.

Re-created virtual input to no effect. Transferred Virtual Input from Gateway to Client and back to Gateway Miniserver. Nil effect.

**Comment by mschlenstedt** [comment]
If this is still open, please provide logfiles (all) in debug mode. It is maybe because only current value is set, but no forecast data?

**Comment by mschlenstedt** [comment]
Closed because of lack of activity.
