### ISSUE TITLE
RFI: Calculation of "Sonnenschein" (Dutch: Zonneschijn)

### ISSUE THREAD

**Issue by Mschuddings** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#55]
Dear,

Thanks for this wonderful plugin, however I was wondering where I could find the calculation for "openweathermap" for the field "Sonnenschein"(That's the name in the Loxone config) ?

Could you point me in the right direction?.

Cheers

**Comment by mschlenstedt** [comment]
This is what Loxone calculates - it is not transmitted by the plugin. You can use solar radioation to set "Sonnenschein" to 1 in LoxConfig.
