### ISSUE TITLE
MOONPERCENT% sichtbar

### ISSUE THREAD

**Issue by scharrin2** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#60]
Vorab möchte ich sagen, dass das Problem schon seit längerer Zeit existiert.

Ich nutze das Plugin mit dem Standard Wetter Service "Weatherbit" und für die Tages- / Stunden-Vorhersage "Dark Sky".

Die Website zeigt die Sichtbarkeit des Mondes nicht an (siehe Screenshot).

Hier steht:

Mond: MOONPERCENT% sichtbar.

![Bildschirmfoto 2021-01-25 um 17 18 42](https://user-images.githubusercontent.com/22325491/105733074-6657d300-5f31-11eb-9a9c-2f93d43d9f9e.png)

**Comment by 4paulpak** [comment]
Dies ist mir auch schon aufgefallen. Allerdings habe ich noch nicht rausgefunden, welche Funktionen diese Information nutzen? Wenn man die Wetterseite in der Loxoneapp öffnet sieht man die Mondinfo nicht.

**Comment by mschlenstedt** [comment]
Das liegt daran, dass euer Wetterdienst die Daten zu Mondsichtbarkeit und Mondphase nicht anbietet.
