### ISSUE TITLE
apache2.service fails to start: Invalid command 'state.ALSA'

### ISSUE THREAD

**Issue by cmonty14** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#66]
Hello,

after upgrading to 4.9.0.3 the apache2.service fails to start.

This is the output of `systemctl status apache2.service`:
```
root@pc5-loxberry:~# systemctl status apache2.service
● apache2.service - The Apache HTTP Server
   Loaded: loaded (/lib/systemd/system/apache2.service; enabled; vendor preset: enabled)                                                                       
  Drop-In: /etc/systemd/system/apache2.service.d
           └─privatetmp.conf
   Active: failed (Result: exit-code) since Thu 2021-07-22 22:46:07 CEST; 4min 25s ago                                                                         
     Docs: https://httpd.apache.org/docs/2.4/
  Process: 731 ExecStart=/usr/sbin/apachectl start (code=exited, status=1/FAILURE)                                                                             

Jul 22 22:46:06 pc5-loxberry systemd[1]: Starting The Apache HTTP Server...
Jul 22 22:46:07 pc5-loxberry apachectl[731]: AH00526: Syntax error on line 1 of /opt/loxberry/system/apache2/sites-enabled/001-weather4lox.conf:               
Jul 22 22:46:07 pc5-loxberry apachectl[731]: Invalid command 'state.ALSA', perhaps misspelled or defined by a module not included in the server configuration  
Jul 22 22:46:07 pc5-loxberry apachectl[731]: Action 'start' failed.
Jul 22 22:46:07 pc5-loxberry apachectl[731]: The Apache error log may have more information.                                                                   
Jul 22 22:46:07 pc5-loxberry systemd[1]: apache2.service: Control process exited, code=exited, status=1/FAILURE                                                
Jul 22 22:46:07 pc5-loxberry systemd[1]: apache2.service: Failed with result 'exit-code'.                                                                      
Jul 22 22:46:07 pc5-loxberry systemd[1]: Failed to start The Apache HTTP Server.
```

This error is pointing to config file _/opt/loxberry/system/apache2/sites-enabled/001-weather4lox.conf_.

Can you please advise how to fix this error?

I have attached the plugin upgrade log for your reference.

In syslog I finf this error message:
`Jul 22 23:35:01 pc5-loxberry sudo[1336]: loxberry : parse error in /etc/sudoers.d/weather4lox near line 4 ; TTY=unknown ; PWD=/ ; USER=root ;`

I assume there are 2 errors that are not related to each other.

THX
[weather4lox.log](https://github.com/mschlenstedt/LoxBerry-Plugin-Weather4Lox/files/6865238/weather4lox.log)

**Comment by cmonty14** [comment]
In syslog I finf this error message:
`ul 22 23:35:01 pc5-loxberry sudo[1336]: loxberry : parse error in /etc/sudoers.d/weather4lox near line 4 ; TTY=unknown ; PWD=/ ; USER=root ;
`

**Comment by mschlenstedt** [comment]
Don't know what happened. There is no string "ALSA.state" in the standard configuration: https://github.com/mschlenstedt/LoxBerry-Plugin-Weather4Lox/blob/master/config/apache2.conf

Try to uninstall and reinstall (no upgrade) the plugin.

**Comment by mschlenstedt** [comment]
Closed due to lack of activity.
