### ISSUE TITLE
WU Update Catcher integration

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#67]
Das Datenfile liegt hier:
`/dev/shm/pwscatchupload_w4l.json`

Hier sind die Werte, die ins File geschrieben werden:
https://github.com/christianTF/LoxBerry-Plugin-PWSCatchUpload/blob/ea3a11678f0a2dfebfedab5dea4e0af093a6fc1b/webfrontend/html/updateweatherstation.php#L130
Werte, die an der Wetterstation nicht existieren, existieren nicht im json.

Im Anhang ist ein Beispielfile meiner Wetterstation:
[pwscatchupload_w4l.zip](https://github.com/mschlenstedt/LoxBerry-Plugin-Weather4Lox/files/7628311/pwscatchupload_w4l.zip)

``` json
{
    "stationid": "WS",
    "cur_date": 1638300816,
    "cur_date_iso": "\"2021-11-30T20:33:36+0100\"",
    "cur_w_ch": 2.72,
    "cur_pr": 1008.46,
    "cur_dp": -7.22,
    "cur_hu": 48,
    "cur_tt": 2.72,
    "cur_w_dir": 321,
    "cur_sr": 4.35,
    "cur_w_sp": 2.16,
    "cur_w_gu": 7.92
}
```

**Comment by mschlenstedt** [comment]
Fixed with #97f31021181065a8c4127e63d836d5bfb4b5dfe7
