### ISSUE TITLE
UDP 7000 erreicht den Miniserver nicht mehr

### ISSUE THREAD

**Issue by TDess** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#68]
Hallo

Seit Anfang dieser Woche bekomme ich keine aktuellen Wetterdaten vom Plugin über den Port 7000 gesendet.
Die Webpage bleibt aber aktuell.

Ich habe das Plugin deinstalliert und neu installiert ==> ohne Erfolg.

UDP Port im Loxberry auf 7001 geändert und den UDP Eingang bei den Wetterdaten im Miniserver geändert.
Daten kommen wieder an.

Alles wieder auf 7000 gesetzt ==> keine Daten kommen am Miniserver an.

Woran kann das liegen?

Miniserver und Loxberry sind am aktuellen Stand.
Alle Plugins sind am neuesten Stand.

**Comment by mschlenstedt** [comment]
Das muss an Deiner LoxoneConfig liegen. Oder bei Dir wird im lokalen Netzwerk Port 7000 geblockt.

Eventuell Port 7000 doppelt vergeben?

**Comment by mschlenstedt** [comment]
Wegen fehlender Rückmeldung geschlossen.
