### ISSUE TITLE
Wetterdatenabruf automatisch funktioniert nicht

### ISSUE THREAD

**Issue by jlauter182** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#69]
Der zykliche Abruf der Wetterdaten funktioniert nicht (zumindest bei mir)
Wetterservice Openweahtermap und Abrufzeit 60 min.
Manuell klappt es nur halt eben nicht alle 60 min.

**Comment by mschlenstedt** [comment]
"Wetterdaten abrufen" ist auf EIN?

**Comment by mschlenstedt** [comment]
Ja, du findest die cronjobs in /opt/loxberry/system/cron 

Vielleicht hat es einen Fehler mit den 60 Minuten. Hast du mal alle 5 Minuten probiert?

**Comment by jlauter182** [comment]
Unter cron.hourly trägt er nix ein

**Comment by mschlenstedt** [comment]
Also bei mir wird der Cronjob angelegt:

![image](https://user-images.githubusercontent.com/16830799/153719757-d7154ecf-9bb1-4f6c-af8f-82ee18e19231.png)

Ganz sicher, dass Du die Abfrage auch aktiviert hast?

![image](https://user-images.githubusercontent.com/16830799/153719802-aa296a83-02dc-4a32-91cd-95579e0fabee.png)

**Comment by jlauter182** [comment]
Warum acüuch immer
