### ISSUE TITLE
Sonnenstrahlung 0-20%

### ISSUE THREAD

**Issue by ERICHKATH** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#7]
Wert wird nicht aktualisiert.

**Comment by tom1104** [comment]
hi,
ich habe (denke ich) das gleiche Problem. In den wetterdaten vom miniserver (wetterdienst Plugin) steht 0-20%
als wert wird bei mir -9999W/m2 geschickt.
wird der wert von Dark sky überhaupt übertragen?
