### ISSUE TITLE
if (defined …

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#70]
Ein Wert 0 wird vom if übersprungen.

https://github.com/mschlenstedt/LoxBerry-Plugin-Weather4Lox/blob/7317d65871fb5fb7b0b4afb4ef20a8612db92bb7/bin/grabber_wu.pl#L205

if(*defined* $wu_response{$resp} and …

zu Forumsanfrage
https://www.loxforum.com/forum/projektforen/loxberry/plugins/157182-plugin-weather4lox-ehemals-wunderground4loxone?p=338076#post338076

**Comment by mr-manuel** [comment]
Das Problem wurde mit Commits am Feb 16, 2022 gelöst und kann somit geschlossen werden.

Bestätigung, dass es wieder geht hier:
https://www.loxforum.com/forum/projektforen/loxberry/plugins/157182-plugin-weather4lox-ehemals-wunderground4loxone?p=338464#post338464
