### ISSUE TITLE
Anzeigen der Mondphase funktioniert nicht mit Weatherbit

### ISSUE THREAD

**Issue by gotome** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#72]
## Problembeschreibung

Im grabber_weatherbit.pl scheint es ein Problem mit der richtigen Anzeige der Mondphase zu geben. Laut deiner Beschreibung müsste die Mondphase, sofern man Weatherbit als Tageswetterdienst deklariert hat, auch angezeigt werden. 

<html>
<body>

cur_moon_p | Moon: % Illuminated | % | Ja | Ja | X | Nur wenn Tagesvorhersage auch von WeatherBit verwendet wird | - | -
-- | -- | -- | -- | -- | -- | -- | -- | --

</body>
</html>

Dies funktioniert bei mir nicht. Das Ergebnis sieht folgendermaßen aus: 
![MoonpercentIssue](https://user-images.githubusercontent.com/40043515/172317751-4d4350ee-2d86-495d-ae1f-778183b6c27c.PNG)

## Nachforschungen

Habe mir den Codeteil rausgesucht wo die Mondphase vom Grabber bearbeitet wird. Hier sieht alles soweit ok aus. 
```pl
print F sprintf("%.0f",$results->{moon_phase}*100), "|";
# Save today's moon phase to include it in current.dat
if ($i eq "2") {
	$moonpercent = sprintf("%.0f",$results->{moon_phase}*100);
}
```

### REST-REQUEST

Habe dann mal selbst über einen REST-Client einen Request ausgeführt. Die Mondphase kommt bei mir auf jeden Fall an und heißt auch `moon_phase`. 

Siehe Codeabschnitt: 
```json
{
      "moonrise_ts": 1654597563,
      "wind_cdir": "WSW",
      "rh": 91,
      "pres": 967,
      "high_temp": 16.4,
      "sunset_ts": 1654628613,
      "ozone": 316.4,
      "moon_phase": 0.540734,
      "wind_gust_spd": 4.3,
      "snow_depth": 0,
      "clouds": 100,
      "ts": 1654552860,
      "sunrise_ts": 1654571242,
      "app_min_temp": 15.2,
      "wind_spd": 1.8,
      "pop": 95,
      "wind_cdir_full": "West-Südwestlich",
      "slp": 1015.3,
      "moon_phase_lunation": 0.29,
      "valid_date": "2022-06-07",
      "app_max_temp": 17.6,
      "vis": 16.598,
      "dewpt": 14.6,
      "snow": 0,
      "uv": 2.8,
      "weather": {
        "icon": "r03d",
        "code": 502,
        "description": "Starker Regen"
      },
      "wind_dir": 244,
      "max_dhi": null,
      "clouds_hi": 100,
      "precip": 26.4678,
      "low_temp": 14,
      "max_temp": 17.6,
      "moonset_ts": 1654560641,
      "datetime": "2022-06-07",
      "temp": 16.2,
      "min_temp": 15.2,
      "clouds_mid": 98,
      "clouds_low": 57
    },
```

Nachdem ich alle möglichen Konfigurationen durch habe, würde ich dich bitte mal darüber zu schauen. Eventuell ist es ja noch ein Konfigurationsproblem von mir. 

Meine Server Settings sind: 
![ServerSettings1](https://user-images.githubusercontent.com/40043515/172319953-839ff739-b9c8-42d4-afe9-c0a6ff2ccd94.PNG)
![ServerSettings2](https://user-images.githubusercontent.com/40043515/172319958-7cc4c13e-1ea0-47c4-8782-af1fe3526ee9.PNG)

Zum Schluss noch ein Dankeschön, denn das Plugin ist ansonsten einmalig 👍

**Comment by mschlenstedt** [comment]
Kannst du bitte einmal testweise den Alternativen Wetterdienst für den Hourly Forecast deaktivieren und dann noch einmal Wetterdaten abrufen?

Wenn der Fehler immer noch Auftritt auch noch einmal den Wunderground Grabber deaktivieren. 

Hilft mir den Fehler weiter einzugrenzen.

**Comment by gotome** [comment]
Habe beide Dienste nacheinander deaktiviert und zwischendurch Daten abgerufen. Problem besteht nach wie vor, es hat sich nie etwas an der Ausgabe geändert. 

Habe dann noch einen Versuch gestartet, wo ich den Daily Forecast alleine deaktiviert habe. Nachdem der alternative Daily und der Default Wetter Service gleich eingestellt waren (beide Weatherbit). Hätte ja sein können, dass der zweite Fetch die Daten des ersten überschreibt. Dem war aber nicht so, auch hier erhalte ich noch immer meine Ausgabe wie oben beschrieben. 

Hier noch der Fetch des Weatherbit Grabbers, vielleicht hilft es bei der Suche:
[20220607_151326_317_grabber_weatherbit.log](https://github.com/mschlenstedt/LoxBerry-Plugin-Weather4Lox/files/8853533/20220607_151326_317_grabber_weatherbit.log)

**Comment by mschlenstedt** [comment]
@gotome  Probiere mal bitte den neuesten Master aus (einfach über Deine bestehende Installation installieren): https://github.com/mschlenstedt/LoxBerry-Plugin-Weather4Lox/archive/refs/heads/master.zip

Damit sollte die Mondphase korrekt gesetzt werden.

**Comment by gotome** [comment]
@mschlenstedt Funktioniert, besten Dank!

**Comment by mschlenstedt** [comment]
Fixed with 72ed58af104e0dc3dc03cb1c78f6f149dd326f52
