### ISSUE TITLE
Could not update to 4.10.0.1

### ISSUE THREAD

**Issue by Letrab** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#78]
Hi,

For 5 days in a row now, I keep getting the message that weather4lox is updated to version 4.10.0.1 .

I am currently on 4.10.0.0 . I just did a manual upgrade to 4.10.0.1, installation was successful, but still the version reflects 4.10.0.0 in the Plugin Management.

Tried a reboot, but still 4.10.0 shows. Should I uninstall and re-install again?

Or is there somewhere a version string forgotten to update?

Thanks!

**Comment by Letrab** [comment]
Oh I see now, the git tag is not on the latest master commit, where the update of the version strings were done.

Could you update the tag please?
Many thanks!

**Comment by mschlenstedt** [comment]
Thanks for the bug report. Should be ok now after you reinstall it one more time ;-)

**Comment by Letrab** [comment]
Yes, all good now, thanks!
