### ISSUE TITLE
After Upgrade to 4.10.0.1; cannot fetch data

### ISSUE THREAD

**Issue by behralex** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#79]
Weather4Lox GRABBER_OPENWEATHER process started
 INFO: LoxBerry Version 2.2.2.2 ( is_raspberry.cfg )
 INFO: Weather 4 Loxone Version 4.10.0.1
 INFO: Loglevel: 6
 INFO: Fetching Current Data for Location lat=49.506088&lon=6.531798
 CRITICAL: Failed to fetch data for lat=49.506088&lon=6.531798. Status Code: 404
 03.12.2022 15:30:03 TASK FINISHED

**Comment by behralex** [comment]
Seit dem Update heute Nacht um 03:15 Uhr tritt dieser Fehler auf, auch ein Restart des Loxberry bringt keine Besserung.

**Comment by mschlenstedt** [comment]
Welchen Wetterservice benutzt du?

**Comment by mschlenstedt** [comment]
Ach, OpenWeather, jetzt sehe ich es auch ;-) Schaue ich mir an.

**Comment by mschlenstedt** [comment]
Kannst Du bitte einmal den letzten Master installieren, nach der Installation einmal die Einstellungen in Weather4Lox abspeichern (ohne Änderung). Danach müsste es wieder funktionieren.

**Comment by behralex** [comment]
Hallo!

Leider erfolglos! Die Installation läuft problemlos, aber auch danach erhalte ich den gleichen Fehler. Die Installation habe ich gleich zweimal durchgeführt einmal ohne das Plugin vorher zu löschen und einmal nachdem ich das Plugin vorher deinstalliert hatte. Auch einen neuen API-Key habe ich generieret und eingebunden. Leider ohne erfolg! 

++++

05.12.2022 21:31:52 TASK STARTED
 Weather4Lox GRABBER_OPENWEATHER process started
 INFO: LoxBerry Version 2.2.2.2 ( is_raspberry.cfg )
 INFO: Weather 4 Loxone Version 4.10.0.1
 INFO: Loglevel: 7
This is /opt/loxberry/bin/plugins/weather4lox/grabber_openweather.pl Version 4.10.0.1
 INFO: Fetching Current Data for Location lat=49.507825&lon=6.539059
URL: https://api.openweathermap.org/data/3.0/onecall?appid=<APX-Key>&lat=49.507825&lon=6.539059&lang=de&units=metric
Status: 401 Unauthorized
 CRITICAL: Failed to fetch data for lat=49.507825&lon=6.539059. Status Code: 401
 05.12.2022 21:31:53 TASK FINISHED
++++++

**Comment by mschlenstedt** [comment]
Ja, du bist nicht für die OneCall API freigeschaltet. https://wiki.loxberry.de/plugins/weather4loxone/start#openweathermap

**Comment by behralex** [comment]
Ja, der ist drin!
Nach der Anpassung funktioniert es teilweise! 

Obwohl ich keine Forcast-Daten abrufe, geschieht dies trotzdem und es werden in Loxone nur Daten von 2016 angezeigt.

![image](https://user-images.githubusercontent.com/119745060/205863766-5d382795-bbf2-4d2e-9578-a011b6058fba.png)

![image](https://user-images.githubusercontent.com/119745060/205863808-3006f4e1-c495-4c96-b0d2-d65ea4d42c92.png)

![image](https://user-images.githubusercontent.com/119745060/205864141-82c02a65-9af8-49f5-bb1a-e3c54262a15d.png)

**Comment by freezeghost** [comment]
I have same problem, but it seems typo at openweather API
I have HTTPS call made by plugin https://api.openweathermap.org/data/2.5/3.0/onecall?appid=!!!!!!!!&lat=50.599714&lon=16.035868&lang=cz&units=metric
previous https://api.openweathermap.org/data/2.5/forecast?appid=8!!!!1&lat=50.599714&lon=16.035868&lang=cz&units=metric&cnt=40
But there is additional 2.5 before 3.0 in type of API call.
Also you have to log into new API 3.0 can't be used old API key!

**Comment by mschlenstedt** [comment]
Yes, already fixed as mentioned above!

Try https://github.com/mschlenstedt/LoxBerry-Plugin-Weather4Lox/archive/refs/heads/master.zip

**Comment by behralex** [comment]
Hi!

Nun ist alles wieder wie vorher! Vielen Dank für den Einsatz!
Viele Grüße 
Alex

**Comment by mschlenstedt** [comment]
Fixed in next version.
