### ISSUE TITLE
Icons are missing at 36h forecast

### ISSUE THREAD

**Issue by Ho551** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#81]
Hello and first of all thank you for the great tool and the last update.
Since the update, the icons are no longer displayed for the 36-hour forecast.
It seems like the translation of the code into the iconcode is missing.

The icons are also missing in Loxone itself. Will these also be rolled out via the plugin?

Thanks!

![image](https://user-images.githubusercontent.com/15242832/206668091-c90429f8-e8d4-4e7a-bdba-247ec0a2c601.png)
![image](https://user-images.githubusercontent.com/15242832/206668141-9ec39c45-c34b-405b-aab4-6b5de3089ced.png)

**Comment by mschlenstedt** [comment]
Which Weatherservice?

It's all fine here with Visual Crossing. Please Right Click on an broken Icon and choose "Open Image in new Tab" and then post the URL here.

**Comment by ErmondCZ** [comment]
Hi its making when using OpenWeatherMap, if its in any hour or daily using.  http://loxoneserver/plugins/weather4lox/icons/silver/d/5.png

**Comment by Ho551** [comment]
It's the same with me.
Also use OpenWeatherMap. 
The image source is addressed as follows: http://loxberry/plugins/weather4lox/icons/dark/d/5.png

**Comment by SaschaH88** [comment]
Hi

I also have the same problem, the pictures are requested with numbers. However, the icons only have pictures with names!
![1](https://user-images.githubusercontent.com/120577258/207617959-cce9b5a5-a921-40ff-a204-7fc31219c97e.JPG)
![2](https://user-images.githubusercontent.com/120577258/207617965-7c4442a6-8db2-480f-abd2-37549643152f.JPG)

Is there already a solution here?
[](url)

**Comment by Ho551** [comment]
@mschlenstedt Thanks!
