### ISSUE TITLE
Falscher Zeitraum wir an den Miniserver übermittelt

### ISSUE THREAD

**Issue by patrick-dmxc** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#82]
Am 12.12.2022 um 17.49
Am 3.12 wurde das Plugin automatisch geupdated, seit dem Werden keine neuen Daten abgerufen
<mb_metadata>
id;name;longitude;latitude;height (m.asl.);country;timezone;utc-timedifference;sunrise;sunset;local date;weekday;local time;temperature(C);feeledTemperature(C);windspeed(km/h);winddirection(degr);wind gust(km/h);low clouds(%);medium clouds(%);high clouds(%);precipitation(mm);probability of Precip(%);snowFraction;sea level pressure(hPa);relative humidity(%);CAPE;picto-code;radiation (W/m2);
</mb_metadata><valid_until>2030-12-31</valid_until>
<station>
;Berlin;13.439;52.449;-9999;Germany;CET;UTC+01.00;07:56;15:55;
03.12.2022;Sat;04; -1.2; -1.2;  0; 70;  0;    0;    0;    0;  0.0;  0;0.0;1017; 86;     0;22;   0;
03.12.2022;Sat;05; -1.3; -5.8; 13; 78; 13;100;100;100;  0.0;-9999;0.0;1019; 84;     0;24;-9999;
03.12.2022;Sat;06; -1.6; -6.0; 13; 76; 13;100;100;100;  0.0;-9999;0.0;1020; 87;     0;24;-9999;
03.12.2022;Sat;07; -1.7; -6.1; 12; 70; 12;100;100;100;  0.0;-9999;0.0;1022; 91;     0;24;-9999;
03.12.2022;Sat;08; -1.9; -6.3; 13; 70; 13;100;100;100;  0.0;-9999;0.0;1023; 91;     0;24;-9999;
03.12.2022;Sat;09; -1.9; -6.5; 14; 71; 14;100;100;100;  0.0;-9999;0.0;1025; 91;     0;24;-9999;
03.12.2022;Sat;10; -1.4; -5.9; 14; 74; 14;100;100;100;  0.0;-9999;0.0;1024; 89;     0;24;-9999;
03.12.2022;Sat;11; -0.8; -5.2; 14; 78; 14;100;100;100;  0.0;-9999;0.0;1024; 86;     0;22;-9999;
03.12.2022;Sat;12; -0.3; -4.5; 13; 81; 13;100;100;100;  0.0;-9999;0.0;1024; 85;     0;22;-9999;
03.12.2022;Sat;13;  0.1; -3.9; 13; 79; 13;100;100;100;  0.0;-9999;0.0;1023; 83;     0;22;-9999;
03.12.2022;Sat;14;  0.2; -3.8; 13; 81; 13;100;100;100;  0.0;-9999;0.0;1023; 82;     0;22;-9999;
03.12.2022;Sat;15;  0.2; -3.6; 12; 81; 12;100;100;100;  0.0;-9999;0.0;1022; 83;     0;22;-9999;
03.12.2022;Sat;16;  0.1; -3.6; 11; 75; 11;100;100;100;  0.0;-9999;0.0;1022; 85;     0;22;-9999;
03.12.2022;Sat;17;  0.1; -3.6; 11; 72; 11;100;100;100;  0.0;-9999;0.0;1022; 86;     0;22;-9999;
03.12.2022;Sat;18;  0.1; -3.5; 11; 73; 11;100;100;100;  0.0;-9999;0.0;1022; 87;     0;22;-9999;
03.12.2022;Sat;19;  0.1; -3.8; 12; 67; 12;100;100;100;  0.0;-9999;0.0;1022; 89;     0;22;-9999;
03.12.2022;Sat;20;  0.1; -3.7; 12; 68; 12;100;100;100;  0.0;-9999;0.0;1022; 89;     0;22;-9999;
03.12.2022;Sat;21;  0.2; -3.4; 11; 67; 11;100;100;100;  0.0;-9999;0.0;1022; 89;     0;22;-9999;
03.12.2022;Sat;22;  0.3; -3.2; 11; 62; 11;100;100;100;  0.0;-9999;0.0;1022; 89;     0;22;-9999;
03.12.2022;Sat;23;  0.4; -3.2; 11; 58; 11;100;100;100;  0.0;-9999;0.0;1022; 90;     0;22;-9999;
04.12.2022;Sun;00;  0.4; -3.3; 11; 60; 11;100;100;100;  0.0;-9999;0.0;1022; 90;     0;22;-9999;
04.12.2022;Sun;01;  0.4; -3.5; 13; 58; 13;100;100;100;  0.0;-9999;0.0;1021; 90;     0;22;-9999;
04.12.2022;Sun;02;  0.5; -3.4; 13; 54; 13;100;100;100;  0.0;-9999;0.0;1021; 91;     0;22;-9999;
04.12.2022;Sun;03;  0.5; -3.3; 12; 52; 12;100;100;100;  0.0;-9999;0.0;1021; 92;     0;22;-9999;
04.12.2022;Sun;04;  0.6; -3.1; 12; 54; 12;100;100;100;  0.0;-9999;0.0;1021; 93;     0;22;-9999;
04.12.2022;Sun;05;  0.8; -2.8; 11; 50; 11;100;100;100;  0.0;-9999;0.0;1021; 93;     0;22;-9999;
04.12.2022;Sun;06;  1.0; -2.6; 11; 51; 11;100;100;100;  0.0;-9999;0.0;1020; 94;     0;22;-9999;
04.12.2022;Sun;07;  1.1; -2.5; 12; 51; 12;100;100;100;  0.0;-9999;0.0;1020; 95;     0;22;-9999;
04.12.2022;Sun;08;  1.2; -2.3; 11; 51; 11;100;100;100;  0.0;-9999;0.0;1020; 95;     0;22;-9999;
04.12.2022;Sun;09;  1.5; -1.9; 11; 50; 11;100;100;100;  0.0;-9999;0.0;1021; 95;     0;22;-9999;
04.12.2022;Sun;10;  1.8; -1.2; 10; 51; 10;100;100;100;  0.0;-9999;0.0;1021; 93;     0;22;-9999;
04.12.2022;Sun;11;  2.2; -0.8; 10; 52; 10;100;100;100;  0.0;-9999;0.0;1021; 92;     0;22;-9999;
04.12.2022;Sun;12;  2.6; -0.2;  9; 52;  9;100;100;100;  0.0;-9999;0.0;1021; 90;     0;22;-9999;
04.12.2022;Sun;13;  2.9;  0.1; 10; 49; 10;100;100;100;  0.0;-9999;0.0;1020; 89;     0;22;-9999;
04.12.2022;Sun;14;  3.0;  0.4;  9; 47;  9;100;100;100;  0.0;-9999;0.0;1020; 89;     0;22;-9999;
04.12.2022;Sun;15;  2.9;  0.3;  9; 43;  9;100;100;100;  0.0;-9999;0.0;1020; 90;     0;22;-9999;
04.12.2022;Sun;16;  2.6; -0.2; 10; 44; 10;100;100;100;  0.0;-9999;0.0;1020; 91;     0;22;-9999;
04.12.2022;Sun;17;  2.5; -0.3;  9; 45;  9;100;100;100;  0.0;-9999;0.0;1020; 92;     0;22;-9999;
04.12.2022;Sun;18;  2.4; -0.3;  9; 44;  9;100;100;100;  0.0;-9999;0.0;1020; 93;     0;22;-9999;
04.12.2022;Sun;19;  2.3; -0.5; 10; 47; 10;100;100;100;  0.0;-9999;0.0;1020; 93;     0;22;-9999;
04.12.2022;Sun;20;  2.4; -0.4;  9; 47;  9;100;100;100;  0.0;-9999;0.0;1021; 93;     0;22;-9999;
04.12.2022;Sun;21;  2.4; -0.2;  8; 42;  8;100;100;100;  0.0;-9999;0.0;1021; 93;     0;22;-9999;
04.12.2022;Sun;22;  2.4; -0.3;  9; 40;  9;100;100;100;  0.0;-9999;0.0;1021; 93;     0;22;-9999;
04.12.2022;Sun;23;  2.5; -0.1;  8; 42;  8;100;100;100;  0.0;-9999;0.0;1021; 93;     0;22;-9999;
05.12.2022;Mon;00;  2.5; -0.1;  9; 38;  9;100;100;100;  0.0;-9999;0.0;1020; 94;     0;22;-9999;
05.12.2022;Mon;01;  2.5;  0.0;  8; 42;  8;100;100;100;  0.0;-9999;0.0;1020; 94;     0;22;-9999;
05.12.2022;Mon;02;  2.6; -0.1;  9; 39;  9;100;100;100;  0.0;-9999;0.0;1020; 94;     0;22;-9999;
05.12.2022;Mon;03;  2.6;  0.1;  9; 44;  9;100;100;100;  0.0;-9999;0.0;1020; 94;     0;22;-9999;
05.12.2022;Mon;04;  2.7;  0.1;  9; 40;  9;100;100;100;  0.0;-9999;0.0;1020; 94;     0;22;-9999;
05.12.2022;Mon;05;  2.8;  0.2;  9; 38;  9;100;100;100;  0.0;-9999;0.0;1020; 94;     0;22;-9999;
05.12.2022;Mon;06;  2.8;  0.3;  9; 37;  9;100;100;100;  0.0;-9999;0.0;1020; 93;     0;22;-9999;
05.12.2022;Mon;07;  2.9;  0.3;  9; 35;  9;100;100;100;  0.0;-9999;0.0;1020; 93;     0;22;-9999;
05.12.2022;Mon;08;  3.0;  0.6;  8; 33;  8;100;100;100;  0.0;-9999;0.0;1020; 93;     0;22;-9999;
05.12.2022;Mon;09;  3.0;  0.9;  7; 31;  7;100;100;100;  0.0;-9999;0.0;1020; 93;     0;22;-9999;
05.12.2022;Mon;10;  3.1;  1.2;  7; 29;  7;100;100;100;  0.0;-9999;0.0;1020; 93;     0;22;-9999;
05.12.2022;Mon;11;  3.2;  1.4;  6; 25;  6;100;100;100;  0.1;-9999;0.0;1020; 93;     0;22;-9999;
05.12.2022;Mon;12;  3.3;  1.6;  6; 20;  6;100;100;100;  0.2;-9999;0.0;1020; 93;     0;23;-9999;
05.12.2022;Mon;13;  3.4;  1.8;  6; 16;  6;100;100;100;  0.2;-9999;0.0;1020; 93;     0;23;-9999;
05.12.2022;Mon;14;  3.4;  1.9;  5; 14;  5;100;100;100;  0.2;-9999;0.0;1020; 93;     0;23;-9999;
05.12.2022;Mon;15;  3.4;  2.1;  5; 12;  5;100;100;100;  0.2;-9999;0.0;1020; 94;     0;23;-9999;
05.12.2022;Mon;16;  3.4;  2.2;  5; 10;  5;100;100;100;  0.1;-9999;0.0;1020; 94;     0;23;-9999;
05.12.2022;Mon;17;  3.3;  2.5;  4;118;  4;100;100;100;  0.4;-9999;0.0;1020; 94;     0;23;-9999;
05.12.2022;Mon;18;  3.3;  2.9;  4;226;  4;100;100;100;  0.7;-9999;0.0;1020; 95;     0;23;-9999;
05.12.2022;Mon;19;  3.2;  3.2;  4;334;  4;100;100;100;  0.9;-9999;0.0;1020; 95;     0;23;-9999;
05.12.2022;Mon;20;  3.2;  2.7;  4;322;  4;100;100;100;  0.8;-9999;0.0;1020; 95;     0;23;-9999;
05.12.2022;Mon;21;  3.1;  2.2;  5;310;  5;100;100;100;  0.7;-9999;0.0;1019; 96;     0;23;-9999;
05.12.2022;Mon;22;  3.1;  1.7;  5;298;  5;100;100;100;  0.5;-9999;0.0;1019; 96;     0;23;-9999;
05.12.2022;Mon;23;  3.1;  1.5;  6;294;  6;100;100;100;  0.5;-9999;0.0;1019; 96;     0;23;-9999;
06.12.2022;Tue;00;  3.0;  1.3;  6;291;  6;100;100;100;  0.5;-9999;0.0;1019; 96;     0;23;-9999;
06.12.2022;Tue;01;  3.0;  1.0;  7;287;  7;100;100;100;  0.5;-9999;0.0;1019; 96;     0;23;-9999;
06.12.2022;Tue;02;  3.0;  0.8;  7;291;  7;100;100;100;  0.7;-9999;0.0;1019; 96;     0;23;-9999;
06.12.2022;Tue;03;  3.0;  0.7;  8;296;  8;100;100;100;  0.8;-9999;0.0;1018; 97;     0;23;-9999;
06.12.2022;Tue;04;  3.0;  0.5;  9;300;  9;100;100;100;  1.0;-9999;0.0;1018; 97;     0;23;-9999;
06.12.2022;Tue;05;  3.2;  0.8;  8;297;  8;100;100;100;  1.0;-9999;0.0;1018; 97;     0;23;-9999;
06.12.2022;Tue;06;  3.3;  1.0;  8;295;  8;100;100;100;  1.0;-9999;0.0;1018; 98;     0;23;-9999;
06.12.2022;Tue;07;  3.5;  1.3;  8;292;  8;100;100;100;  0.9;-9999;0.0;1018; 98;     0;23;-9999;
06.12.2022;Tue;08;  3.6;  1.0; 10;292; 10;100;100;100;  0.8;-9999;0.0;1018; 96;     0;23;-9999;
06.12.2022;Tue;09;  3.7;  0.7; 12;293; 12;100;100;100;  0.5;-9999;0.0;1019; 95;     0;23;-9999;
06.12.2022;Tue;10;  3.8;  0.4; 14;293; 14;100;100;100;  0.3;-9999;0.0;1019; 93;     0;23;-9999;
06.12.2022;Tue;11;  3.9;  0.6; 13;292; 13;100;100;100;  0.0;-9999;0.0;1019; 91;     0;23;-9999;
06.12.2022;Tue;12;  4.0;  0.9; 13;290; 13;100;100;100;  0.0;-9999;0.0;1018; 90;     0;22;-9999;
06.12.2022;Tue;13;  4.1;  1.1; 12;289; 12;100;100;100;  0.0;-9999;0.0;1018; 88;     0;22;-9999;
06.12.2022;Tue;14;  3.9;  0.9; 12;285; 12;100;100;100;  0.0;-9999;0.0;1018; 89;     0;22;-9999;
06.12.2022;Tue;15;  3.6;  0.7; 11;282; 11;100;100;100;  0.0;-9999;0.0;1017; 91;     0;22;-9999;
06.12.2022;Tue;16;  3.4;  0.5; 11;278; 11;100;100;100;  0.0;-9999;0.0;1017; 92;     0;22;-9999;
06.12.2022;Tue;17;  3.4;  0.3; 11;278; 11;100;100;100;  0.0;-9999;0.0;1017; 87;     0;22;-9999;
06.12.2022;Tue;18;  3.3;  0.2; 12;278; 12;100;100;100;  0.0;-9999;0.0;1017; 83;     0;22;-9999;
06.12.2022;Tue;19;  3.2; -0.0; 12;278; 12;100;100;100;  0.0;-9999;0.0;1017; 78;     0;22;-9999;
06.12.2022;Tue;20;  2.7; -0.3; 11;269; 11; 94; 94; 94;  0.0;-9999;0.0;1017; 80;     0;22;-9999;
06.12.2022;Tue;21;  2.2; -0.6; 10;260; 10; 87; 87; 87;  0.0;-9999;0.0;1017; 81;     0;22;-9999;
06.12.2022;Tue;22;  1.7; -0.9;  8;251;  8; 81; 81; 81;  0.0;-9999;0.0;1017; 83;     0;22;-9999;
06.12.2022;Tue;23;  2.0; -0.8;  9;245;  9; 84; 84; 84;  0.0;-9999;0.0;1017; 83;     0;22;-9999;
07.12.2022;Wed;00;  2.3; -0.7; 10;240; 10; 86; 86; 86;  0.0;-9999;0.0;1016; 82;     0;22;-9999;
07.12.2022;Wed;01;  2.5; -0.6; 11;234; 11; 89; 89; 89;  0.0;-9999;0.0;1016; 82;     0;22;-9999;
07.12.2022;Wed;02;  2.5; -0.8; 12;231; 12; 93; 93; 93;  0.0;-9999;0.0;1015; 82;     0;22;-9999;
07.12.2022;Wed;03;  2.4; -1.1; 13;229; 13; 96; 96; 96;  0.0;-9999;0.0;1015; 81;     0;22;-9999;
07.12.2022;Wed;04;  2.4; -1.3; 14;226; 14;100;100;100;  0.0;-9999;0.0;1014; 81;     0;22;-9999;
07.12.2022;Wed;05;  2.3; -1.6; 15;227; 15;100;100;100;  0.0;-9999;0.0;1013; 86;     0;22;-9999;
07.12.2022;Wed;06;  2.2; -1.8; 15;228; 15;100;100;100;  0.0;-9999;0.0;1013; 91;     0;22;-9999;
07.12.2022;Wed;07;  2.1; -2.1; 16;229; 16;100;100;100;  0.0;-9999;0.0;1012; 96;     0;22;-9999;
07.12.2022;Wed;08;  2.4; -1.8; 16;233; 16;100;100;100;  0.1;-9999;0.0;1012; 94;     0;22;-9999;
07.12.2022;Wed;09;  2.7; -1.4; 17;236; 17;100;100;100;  0.2;-9999;0.0;1012; 93;     0;23;-9999;
07.12.2022;Wed;10;  3.0; -1.1; 17;240; 17;100;100;100;  0.3;-9999;0.0;1012; 91;     0;23;-9999;
07.12.2022;Wed;11;  2.8; -1.3; 17;248; 17;100;100;100;  0.5;-9999;0.0;1012; 92;     0;23;-9999;
07.12.2022;Wed;12;  2.7; -1.5; 17;255; 17;100;100;100;  0.7;-9999;0.0;1011; 93;     0;23;-9999;
07.12.2022;Wed;13;  2.5; -1.8; 18;263; 18;100;100;100;  0.9;-9999;0.0;1011; 94;     0;23;-9999;
07.12.2022;Wed;14;  2.5; -1.6; 16;262; 16; 99; 99; 99;  0.0;-9999;0.0;1011; 91;     0;23;-9999;
07.12.2022;Wed;15;  2.5; -1.4; 15;262; 15; 98; 98; 98;  0.0;-9999;0.0;1011; 89;     0;24;-9999;
07.12.2022;Wed;16;  2.4; -1.1; 13;261; 13; 97; 97; 97;  0.0;-9999;0.0;1011; 86;     0;24;-9999;
07.12.2022;Wed;17;  2.4; -1.4; 14;255; 14; 94; 94; 94;  0.0;-9999;0.0;1011; 84;     0;24;-9999;
07.12.2022;Wed;18;  2.4; -1.6; 16;248; 16; 91; 91; 91;  0.0;-9999;0.0;1011; 82;     0;22;-9999;
07.12.2022;Wed;19;  2.4; -1.9; 17;242; 17; 88; 88; 88;  0.0;-9999;0.0;1011; 80;     0;22;-9999;
07.12.2022;Wed;20;  2.3; -1.9; 16;256; 16; 92; 92; 92;  0.0;-9999;0.0;1011; 84;     0;22;-9999;
07.12.2022;Wed;21;  2.1; -1.8; 15;269; 15; 96; 96; 96;  0.0;-9999;0.0;1012; 88;     0;22;-9999;
07.12.2022;Wed;22;  2.0; -1.8; 14;283; 14;100;100;100;  0.0;-9999;0.0;1012; 92;     0;22;-9999;
07.12.2022;Wed;23;  1.7; -1.9; 12;280; 12;100;100;100;  0.0;-9999;0.0;1012; 89;     0;22;-9999;
08.12.2022;Thu;00;  1.4; -1.9; 11;277; 11;100;100;100;  0.0;-9999;0.0;1012; 85;     0;22;-9999;
08.12.2022;Thu;01;  1.1; -2.0; 10;274; 10;100;100;100;  0.0;-9999;0.0;1012; 82;     0;22;-9999;
08.12.2022;Thu;02;  0.9; -2.1;  9;264;  9;100;100;100;  0.0;-9999;0.0;1012; 83;     0;22;-9999;
08.12.2022;Thu;03;  0.7; -2.1;  8;254;  8;100;100;100;  0.0;-9999;0.0;1012; 85;     0;22;-9999;
08.12.2022;Thu;04;  0.4; -2.2;  8;244;  8;100;100;100;  0.0;-9999;0.0;1012; 86;     0;22;-9999;
</station>

**Comment by mschlenstedt** [comment]
?

**Comment by patrick-dmxc** [comment]
Sorry, bin auf enter gekommen bevor ich fertig war

**Comment by mschlenstedt** [comment]
Ach so ;-)

**Comment by mschlenstedt** [comment]
Welcher Wetterdienst? Laß mich raten: OpenWeatherMap?

**Comment by patrick-dmxc** [comment]
ja

**Comment by mschlenstedt** [comment]
Installiere bitte mal diese Version: https://github.com/mschlenstedt/LoxBerry-Plugin-Weather4Lox/archive/refs/heads/master.zip

**Comment by patrick-dmxc** [comment]
Hab ich gemacht und Wetterdaten abgerufen, immer noch werden mir Vorhersagen vom 3.-8. angezeigt

**Comment by patrick-dmxc** [comment]
Ok, also kommt der fehler von der OpenWeatherMap-API....
DAnke für die hilfe
