### ISSUE TITLE
No actual data in the Emulator

### ISSUE THREAD

**Issue by michl1003** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#84]
hello, i use the Wather4Loxone plugin but there are no correct or actual data...

i tried with all posible Weather-services but i can't fix it... i always see only this when i try to test the emulator: 

`<mb_metadata>
id;name;longitude;latitude;height (m.asl.);country;timezone;utc-timedifference;sunrise;sunset;local date;weekday;local time;temperature(C);feeledTemperature(C);windspeed(km/h);winddirection(degr);wind gust(km/h);low clouds(%);medium clouds(%);high clouds(%);precipitation(mm);probability of Precip(%);snowFraction;sea level pressure(hPa);relative humidity(%);CAPE;picto-code;radiation (W/m2);
</mb_metadata><valid_until>2030-12-31</valid_until>
<station>
;;;;;;;UTC.;:;:;
31.12.2008;Wed;23;  0.0;  0.0;  0;  0;  0;  0;  0;  0;  0.0;  0;0.0;   0;  0;     0; 0;   0;
</station>`

time on the loxberry is correct (synced with miniserver and local NTP)
here my config in W4L:
![image](https://user-images.githubusercontent.com/104894941/207839333-eab6e0af-8514-4659-aa95-08d482dba367.png)

**Comment by mschlenstedt** [comment]
Switch to Visual Crossings for Current weather and Forecasts.

Enable Emulator:

![image](https://user-images.githubusercontent.com/16830799/207839927-1e55746e-14e7-4610-b04e-5abb66bb0eea.png)

Enabling Debug logging in logging tab. Fetch weather data manually and after that, attach here newest and full logfiles of "Grabber_visualcrossing" and "Datatoloxone" (remove API Key).

**Comment by michl1003** [comment]
hello, thanks for response, Emulator is actually activated... her are the logs...
![image](https://user-images.githubusercontent.com/104894941/207853444-3e416a01-941a-466c-ba81-9ba4c5a671cf.png)
![image](https://user-images.githubusercontent.com/104894941/207853534-a5b09d04-b21c-4234-86a7-d020c565c1c1.png)
![image](https://user-images.githubusercontent.com/104894941/207856478-c6066f8a-c1b0-425e-869a-bf00b69e5865.png)
![image](https://user-images.githubusercontent.com/104894941/207856736-c4da5bae-9bbb-4c0e-9bc9-f2d275e5b862.png)
![image](https://user-images.githubusercontent.com/104894941/207856999-bd9d100f-2b73-491b-ac7d-7ab0a5e5c3c3.png)
![image](https://user-images.githubusercontent.com/104894941/207857095-567097f3-d028-4936-8746-8e4424ba5f1b.png)

i can'f find a section "Grabber_Visualcrossing

**Comment by mschlenstedt** [comment]
Visual Crossing log looks good. All needed data is here and saved. After fetching weather from Visual Crossing - have you checked the output of the Emulator? It should be there.

It will not work with OpenWeatherMap. The grabber is broken because they changed their API. You will not have success at the moment with OpenWeatherMap.

Furthermore I think you have a problem with the nameresolving or something else on your system. Cannot fix this from here - I saw that you are on a VM, maybe here's a problem - don't know.

**Comment by mschlenstedt** [comment]
Closed because of no answer. Reopen if problem still exist or post in the Loxone forum.
