### ISSUE TITLE
[User Story] As a Loxone Beta-User I want to have the Beta-URL for Loxone weather integrated in DNS Masq inside the plugin

### ISSUE THREAD

**Issue by tt2g89** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#85]
Hi Michael,
here's a User Story for the Lox-Beta Users using W4L and I would like it very much, if you could implement it, when you find time for it.

As a Loxone Beta-User 
I want to have the Beta-URL for Loxone weather integrated in DNS Masq inside the plugin
to have a working plugin, no matter, if the PROD- or BETA-version of Loxone Miniserver is in use.

**ACs:**
1. Beta-URL address=/weather-beta.loxone.com/LOXBERRY_IP is included into the config of DNS Masq inside the W4L plugin
2. No seperate DNS Masq plugin installation is needed

Thanks a lot in advance and best regards,
Thomas

**Comment by mschlenstedt** [comment]
Yes, this is really no big deal. I will create a new bugfix version today or tomorrow and will include this, too.
