### ISSUE TITLE
dnsmasq will not be installed

### ISSUE THREAD

**Issue by andres291** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#87]
The plugin does not install the dnsmasq. Querying the data from miniserver using LoxBerry Cloud Weather Emulator does not work.

The following NEW packages will be installed:
dnsmasq dnsmasq-base
0 upgraded, 2 newly installed, 1 reinstalled, 0 to remove and 5 not upgraded.
Need to get 416 kB/504 kB of archives.
After this operation, 921 kB of additional disk space will be used.
Ign:1 http://ftp.halifax.rwth-aachen.de/raspbian/raspbian buster/main armhf dnsmasq-base armhf 2.80-1
Ign:2 http://ftp.halifax.rwth-aachen.de/raspbian/raspbian buster/main armhf dnsmasq all 2.80-1
Ign:1 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf dnsmasq-base armhf 2.80-1
Ign:2 http://ftp.gwdg.de/pub/linux/debian/raspbian/raspbian buster/main armhf dnsmasq all 2.80-1
Err:1 http://ftp.agdsn.de/pub/mirrors/raspbian/raspbian buster/main armhf dnsmasq-base armhf 2.80-1
404 Not Found [IP: 2a00:8a60:e012:a00::21 80]
Err:2 http://ftp.agdsn.de/pub/mirrors/raspbian/raspbian buster/main armhf dnsmasq all 2.80-1
404 Not Found [IP: 2a00:8a60:e012:a00::21 80]
E: Failed to fetch http://ftp.agdsn.de/pub/mirrors/raspbian/raspbian/pool/main/d/dnsmasq/dnsmasq-base_2.80-1_armhf.deb 404 Not Found [IP: 2a00:8a60:e012:a00::21 80]
E: Failed to fetch http://ftp.agdsn.de/pub/mirrors/raspbian/raspbian/pool/main/d/dnsmasq/dnsmasq_2.80-1_all.deb 404 Not Found [IP: 2a00:8a60:e012:a00::21 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by mschlenstedt** [comment]
Problem with your apt installation or your network setup.  Your Loxberry cannot reach the apt servers.

**Comment by andres291** [comment]
Thanks, needed to update Loxberry after new installation.

**Comment by andres291** [comment]
Now all is green in the plugin at loxberry, emulator is running and test works, dns ip is set in the miniserver at both entries, miniserver calls weather.loxone.com:6066 but no weather shows up in the loxone app.

5	14:19:10.794	Loxone Miniserver		Request	weather.loxone.com:6066	/forecast/?user=loxone_504F94A0A46D&coord=13.3230,52.6320&asl=55&format=1&new_api=1	GET /forecast/?user=loxone_504F94A0A46D&coord=13.3230,52.6320&asl=55&format=1&new_api=1 HTTP/1.1\r\nHost: weather.loxone.com:6066\r\nUser-Agent: [en]\r\nContent-Type: text/html; charset=utf-8\r\nConnection: close

6	14:19:10.794	Loxone Miniserver		Response	weather.loxone.com:6066	/forecast/?user=loxone_504F94A0A46D&coord=13.3230,52.6320&asl=55&format=1&new_api=1	HTTP/1.1 200 OK\r\ncross-origin-embedder-policy: require-corp\r\ncross-origin-opener-policy: same-origin\r\ncross-origin-resource-policy: same-origin\r\nx-dns-prefetch-control: off\r\nexpect-ct: max-age=0\r\nx-frame-options: SAMEORIGIN\r\nstrict-transport-security: max-age=15552000; includeSubDomains\r\nx-download-options: noopen\r\nx-content-type-options: nosniff\r\norigin-agent-cluster: ?1\r\nx-permitted-cross-domain-policies: none\r\nreferrer-policy: no-referrer\r\nx-xss-protection: 0\r\ncontent-security-policy: default-src 'self';...

**Comment by mschlenstedt** [comment]
You can try to install dnsmasq package on the console with "sudo apt-get install....". Your apt installation is broken - still. Maybe this shows you some kind of error message.

**Comment by andres291** [comment]
Thank you, @mschlenstedt. I had realy to delete the whole SD card, install Loxberry, update Loxberry, install the weather plugin. Now it works. I used the plugin already for some years, thats why I'm suprised that I had problems with a new installation.
