### ISSUE TITLE
Comment out the logfile names to have seperate logfiles each run again

### ISSUE THREAD

**Issue by mschlenstedt** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#94]

**Comment by mr-manuel** [comment]
https://github.com/mschlenstedt/LoxBerry-Plugin-Weather4Lox/blob/03a785d43facbaf4102a914d7484a80ca95f757d/bin/cronjob.pl#L55-L56

https://github.com/mschlenstedt/LoxBerry-Plugin-Weather4Lox/blob/03a785d43facbaf4102a914d7484a80ca95f757d/bin/fetch.pl#L66-L67
