### ISSUE TITLE
add extra entries for wind directions in language file

### ISSUE THREAD

**Issue by jslits** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#95]
what I saw is that the wind direction needs to have an extra section with abbreviations, for example: s sw sws.
given this example: for german and english it's the same abbreviation, for dutch it's z zw zwz

**Comment by mschlenstedt** [comment]
Where do we use these abbreviations? We already have translations for the long description. Currently I do not know where we use abbreviations at all...

https://github.com/mschlenstedt/LoxBerry-Plugin-Weather4Lox/blob/7a139fdc36976e01596da5c968772d1a5f7bbce6/templates/lang/language_nl.ini#L99-L106

**Comment by mschlenstedt** [comment]
No answer for month - we close this issue. Reopen it if nessessary.
