### ISSUE TITLE
Dark Sky API discontinued

### ISSUE THREAD

**Issue by Noschvie** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#96]
The Dark Sky API will no longer provide weather data.

Dieses Feature sollte im Plugin aufgelöst und gelöscht werden.

**Comment by mschlenstedt** [comment]
Ja, bis zum 31.03. ging der Zugang noch. Im Wiki steht die Abkündigung von DarkSky schon über zwei Jahre.  

Bisher funktionierten die Zugänge noch, daher wurde es auch nicht entfernt.

**Comment by Noschvie** [comment]
Vielleicht habe ich mich schlecht ausgedrückt: wegen der Einstellung des Dark Sky APIs, sollte das Dark Sky Feature im Plugin aufgelöst und gelöscht werden.

**Comment by mschlenstedt** [comment]
Ja, werden wir mit dem nächsten Update auch machen. Aber aktuell ist es halt noch drin, weil es bis vor ein paar Tagen ja auch noch funktionierte.

**Comment by mschlenstedt** [comment]
Erledigt.
