### ISSUE TITLE
Grabber Daten ohne Funktion / Fehler

### ISSUE THREAD

**Issue by KSchwind81** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#98]
Hallo. Seit kurzem werden die Grabber Daten (Außentemperatur) nicht mehr in der App angezeigt. Ein Aus- und Einschalten bringt folgende Meldung beim Speichern:

Software error:
Wide character in subroutine entry at /opt/loxberry/webfrontend/htmlauth/plugins/weather4lox/index.cgi line 1229.

11.04.2023 07:48:02 TASK STARTED
Weather4Lox GRABBER_DARKSKY process started
INFO: LoxBerry Version 2.2.2.2 ( is_raspberry.cfg )
INFO: Weather 4 Loxone Version 4.10.0.2
INFO: Loglevel: 3
CRITICAL: Failed to fetch data for 50.3937304,7.3860356. Status Code: 500
11.04.2023 07:48:27 TASK FINISHED

**Comment by mschlenstedt** [comment]
Darksky hat seinen Dienst zum 31.3.23 eingestellt. Wechsel auf Visual Crossing.

**Comment by KSchwind81** [comment]
Tatsache. Obwohl DarkSky noch Daten liefert udn der Grabber ja eigentlich nichts damit zu tun hat (denke ich in meiner Unwissenheit einfach mal).
Habe auf crossing ugestellt und der Grabber geht / Fehler ist auch weg.
